{
  "hash": "0c02e300937e63605a214d3dfa54c023",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Hands-on 5.b: Local Measures of Spatial Autocorrelationn\"\nauthor: Johsuan Huang\ndate: 2025-09-25\ndate-modified: \"last-modified\"\ndescription: \"\"\nformat: html\nexecute:\n  echo: true\n  eval: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1 Overview\n\nLocal Measures of Spatial Autocorrelation (LMSA) focus on the relationships between each observation and its surroundings, rather than providing a single summary of these relationships across the map. In this sense, they are not summary statistics but scores that allow us to learn more about the spatial structure in our data.\n\nThe general intuition behind the metrics however is similar to that of global ones. Some of them are even mathematically connected, where the global version can be decomposed into a collection of local ones. One such example are **Local Indicators of Spatial Association (LISA)**. Beside LISA, Getis-Ord’s Gi-statistics will be introduce as an alternative LMSA statistics that present complementary information or allow us to obtain similar insights for geographically referenced data.\n\nIn this hands-on exercise, we will learn how to compute Local Measures of Spatial Autocorrelation (LMSA) by using [**sfdep**](https://sfdep.josiahparry.com/) package. By the end to this hands-on exercise, we will be able to:\n\n-   import geospatial data using appropriate function(s) of **sf** package,\n-   import csv file using appropriate function of **readr** package,\n-   perform relational join using appropriate join function of **dplyr** package,\n-   compute Local Indicator of Spatial Association (LISA) statistics for detecting clusters and outliers by using appropriate functions **sfdep** package;\n-   compute Getis-Ord’s Gi-statistics for detecting hot spot or/and cold spot area by using appropriate functions of **sfdep** package; and\n-   to visualise the analysis output by using **tmap** package.\n\n# 2 Getting Started\n\n## 2.1 The analytical question\n\nIn spatial policy, one of the main development objective of the local government and planners is to ensure equal distribution of development in the province. Our task in this study, hence, is to apply appropriate spatial statistical methods to discover if development are even distributed geographically. If the answer is **No**. Then, our next question will be “is there sign of spatial clustering?”. And, if the answer for this question is yes, then our next question will be “**where are these clusters?**”\n\nIn this case study, we are interested to examine the spatial pattern of a selected development indicator (i.e. GDP per capita) of [Hunan Provice](https://en.wikipedia.org/wiki/Hunan), People Republic of China.\n\n## 2.2 The Study Area and Data\n\nTwo data sets will be used in this hands-on exercise, they are:\n\n-   Hunan province administrative boundary layer at county level. This is a geospatial data set in ESRI shapefile format.\n\n-   Hunan_2012.csv: This csv file contains selected Hunan’s local development indicators in 2012.\n\n## 2.3 Setting the Analytical Toolls\n\n| Library | Desc |\n|-----------------|------------------------------------------------------|\n| [sf](https://r-spatial.github.io/sf/) | handling geospatial data |\n| [tmap](https://cran.r-project.org/web/packages/tmap/index.html) | visualization for geospatial data |\n| tidyverse | handling data including packages **readr**, **tidyr and dplyr** |\n| knitr | generate elegant, flexible, and fast dynamic report |\n| sfdep | compute spatial weights, global and local spatial autocorrelation statistics |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tmap, tidyverse,knitr,sfdep,ggrepel)\n```\n:::\n\n\n\n## 2.4 Getting the Data Into R Environment\n\nIn this section, we will learn how to bring a geospatial data and its associated attribute table into R environment. The geospatial data is in ESRI shapefile format and the attribute table is in csv fomat.\n\n### 2.4.1 Import shapefile\n\nThe code chunk below uses [`st_read()`](https://r-spatial.github.io/sf/reference/st_read.html) of **sf** package to import Hunan shapefile into R. The imported shapefile will be **simple features** Object of **sf**.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- st_read(dsn = \"data/geospatial\", \n                 layer = \"Hunan\") %>%\n  st_transform(crs = 32650)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `Hunan' from data source \n  `/Users/johsuan/johsuanh/ISSS626-GAA/Hands-on/Hands-on-Ex05/data/geospatial' \n  using driver `ESRI Shapefile'\nSimple feature collection with 88 features and 7 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 108.7831 ymin: 24.6342 xmax: 114.2544 ymax: 30.12812\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:32650 \n  wkt:\nPROJCRS[\"WGS 84 / UTM zone 50N\",\n    BASEGEOGCRS[\"WGS 84\",\n        ENSEMBLE[\"World Geodetic System 1984 ensemble\",\n            MEMBER[\"World Geodetic System 1984 (Transit)\"],\n            MEMBER[\"World Geodetic System 1984 (G730)\"],\n            MEMBER[\"World Geodetic System 1984 (G873)\"],\n            MEMBER[\"World Geodetic System 1984 (G1150)\"],\n            MEMBER[\"World Geodetic System 1984 (G1674)\"],\n            MEMBER[\"World Geodetic System 1984 (G1762)\"],\n            MEMBER[\"World Geodetic System 1984 (G2139)\"],\n            MEMBER[\"World Geodetic System 1984 (G2296)\"],\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]],\n            ENSEMBLEACCURACY[2.0]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4326]],\n    CONVERSION[\"UTM zone 50N\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",117,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",0.9996,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",500000,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",0,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"(E)\",east,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"(N)\",north,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Navigation and medium accuracy spatial referencing.\"],\n        AREA[\"Between 114°E and 120°E, northern hemisphere between equator and 84°N, onshore and offshore. Brunei. China. Hong Kong. Indonesia. Malaysia - East Malaysia - Sarawak. Mongolia. Philippines. Russian Federation. Taiwan.\"],\n        BBOX[0,114,84,120]],\n    ID[\"EPSG\",32650]]\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\nThe raw data is in WGS 84 geographic coordinates system. For geospatial analysis, it is appropriate to use projected coordinates system.\n\nIn the code chunk above, `st_transform()` is used to transform Hunan geospatial data from WGS 84 to UTM zone 50N (i.e. EPSG: 32650).\n\nArea of use: **Between 114°E and 120°E**, northern hemisphere between equator and 84°N, onshore and offshore. Brunei. China. Hong Kong. Indonesia. Malaysia - East Malaysia - Sarawak. Mongolia. Philippines. Russian Federation. Taiwan\n:::\n\nAfter importing the shape file, let's plot the graph:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg=\"#f6f6f6\")\nplot(hunan)\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\n### 2.4.2 Import CSV File\n\nNext, we will import *Hunan_2012.csv* into R by using *read_csv()* of **readr** package. The output is R dataframe class.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan2012 <- read_csv(\"data/aspatial/Hunan_2012.csv\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(hunan2012))\n```\n\n::: {.cell-output-display}\n\n\n|County    |City       | avg_wage| deposite|    FAI| Gov_Rev| Gov_Exp|     GDP| GDPPC|     GIO|   Loan|  NIPCR|  Bed|    Emp|  EmpR| EmpRT| Pri_Stu| Sec_Stu| Household| Household_R| NOIP| Pop_R|    RSCG| Pop_T|     Agri| Service| Disp_Inc|      RORP|    ROREmp|\n|:---------|:----------|--------:|--------:|------:|-------:|-------:|-------:|-----:|-------:|------:|------:|----:|------:|-----:|-----:|-------:|-------:|---------:|-----------:|----:|-----:|-------:|-----:|--------:|-------:|--------:|---------:|---------:|\n|Anhua     |Yiyang     |    30544|  10967.0| 6831.7|  456.72|  2703.0| 13225.0| 14567|  9276.9| 3954.9| 3528.3| 2718| 494.31| 441.4| 338.0|  54.175|  32.830|     290.4|       234.5|  101| 670.3| 5760.60| 910.8| 4942.253|  5414.5|    12373| 0.7359464| 0.8929619|\n|Anren     |Chenzhou   |    28058|   4598.9| 6386.1|  220.57|  1454.7|  4941.2| 12761|  4189.2| 2555.3| 3271.8|  970| 290.82| 255.4|  99.4|  33.171|  17.505|     104.6|       121.9|   34| 243.2| 2386.40| 388.7| 2357.764|  3814.1|    16072| 0.6256753| 0.8782065|\n|Anxiang   |Changde    |    31935|   5517.2| 3541.0|  243.64|  1779.5| 12482.0| 23667|  5108.9| 2806.9| 7693.7| 1931| 336.39| 270.5| 205.9|  19.584|  17.819|     148.1|       135.4|   53| 346.0| 3957.90| 528.3| 4524.410| 14100.0|    16610| 0.6549309| 0.8041262|\n|Baojing   |Hunan West |    30843|   2250.0| 1005.4|  192.59|  1379.1|  4087.9| 14563|  3623.5| 1253.7| 4191.3|  927| 195.17| 145.6| 116.4|  19.249|  11.831|      73.2|        69.9|   18| 184.1|  768.04| 281.3| 1118.561|   541.8|    13455| 0.6544614| 0.7460163|\n|Chaling   |Zhuzhou    |    31251|   8241.4| 6508.4|  620.19|  1947.0| 11585.0| 20078|  9157.7| 4287.4| 3887.7| 1449| 330.29| 299.0| 154.0|  33.906|  20.548|     148.7|       139.4|  106| 301.6| 4009.50| 578.4| 3793.550|  5444.0|    20461| 0.5214385| 0.9052651|\n|Changning |Hengyang   |    28518|  10860.0| 7920.0|  769.86|  2631.6| 19886.0| 24418| 37392.0| 4242.8| 9528.0| 3605| 548.61| 415.1| 273.7|  81.831|  44.485|     211.2|       211.7|  115| 448.2| 5220.40| 816.3| 6430.782| 13074.6|    20868| 0.5490628| 0.7566395|\n\n\n:::\n:::\n\n\n\n### 2.3.3 Perform Relational Join\n\nThe code chunk below will be used to update the attribute table of *hunan*’s SpatialPolygonsDataFrame with the attribute fields of *hunan2012* dataframe. This is performed by using *left_join()* of **dplyr** package.\n\nAfter performing a left join, we remove unnecessary columns and retain only 'NAME_2', 'ID_3', 'NAME_3', 'ENGTYPE_3', 'County', and 'GDPPC' for further analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhunan <- left_join(hunan,hunan2012,\n                   by = \"County\")  %>%\n  select(1:4, 7, 15)\nkable(head(hunan,5))\n```\n\n::: {.cell-output-display}\n\n\n|NAME_2  |  ID_3|NAME_3  |ENGTYPE_3   |County  | GDPPC|geometry                       |\n|:-------|-----:|:-------|:-----------|:-------|-----:|:------------------------------|\n|Changde | 21098|Anxiang |County      |Anxiang | 23667|POLYGON ((22320.48 3301894,... |\n|Changde | 21100|Hanshou |County      |Hanshou | 20981|POLYGON ((35522.96 3230355,... |\n|Changde | 21101|Jinshi  |County City |Jinshi  | 34592|POLYGON ((5120.127 3285521,... |\n|Changde | 21102|Li      |County      |Li      | 24473|POLYGON ((-43433.9 3326204,... |\n|Changde | 21103|Linli   |County      |Linli   | 25554|POLYGON ((-19307.27 3304609... |\n\n\n:::\n\n```{.r .cell-code}\nclass(hunan)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"sf\"         \"data.frame\"\n```\n\n\n:::\n:::\n\n\n\n# 3 Visualize Regional Development Indicator\n\nNow, we are going to prepare a basemap and a choropleth map showing the distribution of GDP Per Capita (GDPPC) 2012 by using **tmap** package:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nequal <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"equal\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_text(\"NAME_3\", size=0.6)+\n tm_title(\"Equal interval classification\",\n           position = tm_pos_out(\"center\", \"top\", \"center\")) +\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"),\n    bg.color = \"#f6f6f6\",\n    frame = FALSE)\n\nquantile <- tm_shape(hunan) +\n  tm_polygons(fill = \"GDPPC\",\n              fill.scale = tm_scale_intervals(\n                style = \"quantile\",\n                n = 5,\n                values = \"brewer.blues\")) +\n  tm_text(\"NAME_3\", size=0.6)+\n tm_title(\"Quantile classification\",\n           position = tm_pos_out(\"center\", \"top\", \"center\")) +\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"),\n    bg.color = \"#f6f6f6\",\n    frame = FALSE)\n\ntmap_arrange(equal, \n             quantile, \n             asp=1, \n             ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-8-1.png){width=1152}\n:::\n:::\n\n\n\n# 4 Local Indicators of Spatial Association(LISA)\n\nLocal Indicators of Spatial Association (LISA) are statistics that measure spatial patterns at a local level, unlike global measures (like Moran’s I or Geary’s C) which summarize the whole area. It evaluate the **existence of clusters and/or outliers**:\n\n-   **Clusters:** neighboring areas with similar values (high-high or low-low).\n-   **Outliers:** areas that are very different from their neighbors (high-low or low-high).\n\nFor instance if we are studying distribution of GDP per capita of Hunan Provice, People Republic of China, **local clusters** in GDP per capita mean that there are counties that have higher or lower rates than is to be expected by chance alone;The idea is to see whether these patterns are **just random** or statistically significant.\n\nIn this section, we will learn how to apply appropriate Local Indicators for Spatial Association (LISA), especially local Moran’I to detect cluster and/or outlier from GDP per capita 2012 of Hunan Province, PRC.\n\n## 4.1 Computing Contiguity Spatial Weights\n\nBefore we can compute the local spatial autocorrelation statistics, we need to construct a spatial weights of the study area. The spatial weights is used to define the neighbourhood relationships between the geographical units (i.e. county) in the study area.\n\nIn the code chunk below, [`st_contiguity()`](https://sfdep.josiahparry.com/reference/st_contiguity) of **sfdep** package is used to compute contiguity weight matrices for the study area. This function builds a neighbours list based on regions with contiguous boundaries. If you look at the documentation you will see that you can pass a “queen” argument that takes TRUE or FALSE as options. If you do not specify this argument the default is set to TRUE, that is, if you don’t specify queen = FALSE this function will return a list of first order neighbours using the Queen criteria.\n\nNext, [`st_weights()`](https://sfdep.josiahparry.com/reference/st_weights) is used to calculate polygon spatial weights from the *nb* list.\n\n`st_weights()` provides three arguments, they are:\n\n-   nb: A neighbor list object as created by `st_neighbors()`.\n\n-   style: Default “W” for row standardized weights. This value can also be “B”, “C”, “U”, “minmax”, and “S”. B is the basic binary coding, W is row standardised (sums over all links to n), C is globally standardised (sums over all links to n), U is equal to C divided by the number of neighbours (sums over all links to unity), while S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n).\n\n-   allow_zero: If TRUE, assigns zero as lagged value to zone without neighbors.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwm_q <- hunan %>%\n  mutate(nb = st_contiguity(geometry, queen = TRUE),\n         wt = st_weights(nb, style = \"W\"),\n         .before = 1) \n```\n:::\n\n\n\n::: callout-note\n## How to read the result?\n\nThe summary report above shows that:\n\n-   There are total 88 area units/conties in Hunan.\n-   Across all units, there are 448 total neighbor connections, where one region is considered a neighbor of another.\n-   Only around 5.8% (448 / (88\\*88) ) of all possible region-to-region connections are considered neighbors\n-   On average, each region has around 5 neighbors (448/88) under Queen contiguity.\n-   The Link number distribution says 2 regions (Region 30 & 65) has only 1 neighbor, 2 regions has 2 neighbors,..,1 region (Region 85) has 11 neighbors\n:::\n\n## 4.2 Row-standardised Weights Matrix\n\nNext, we need to assign weights to each neighboring polygon. By doing this, we can **measure “influence” of neighboring regions.**\n\nIn our case, each neighboring polygon will be assigned **equal weight** (**style=“W”**). This is accomplished by assigning the fraction: **1/n** to each neighboring county then summing the weighted income values. While the method is simple and intuitive, the drawback is that boundary regions have fewer neighbors, so their lagged values might be biased, thus potentially over- or under-estimating the true nature of the spatial autocorrelation in the data\n\nOther robust method includes **Binary weights (`style=\"B\"`)** - Each neighbor just gets **1**, non-neighbors get **0**.\n\n-   The input of [`nb2listw()`](https://r-spatial.github.io/spdep/reference/nb2listw.html) must be an object of class **nb**. The syntax of the function has two major arguments, namely style and zero.poly.\n\n-   The zero.policy=TRUE option allows for lists of **non-neighbors**. R will **allow observations with no neighbors**, treating them as having **weights = 0**. If FALSE(the default), R will throw an **error** if any observation has no neighbors.\n\n-   *style* can take values “W”, “B”, “C”, “U”, “minmax” and “S”. B is the basic binary coding, W is row standardised (sums over all links to n), C is globally standardised (sums over all links to n), U is equal to C divided by the number of neighbours (sums over all links to unity), while S is the variance-stabilizing coding scheme proposed by Tiefelsdorf et al. 1999, p. 167-168 (sums over all links to n)\n\n::: callout-note\n## How to read the result?\n\n-   n: Number of observations (regions/polygons). Here, 88 regions/polygons.\n-   nn: Total number of neighbor pairs. Together, these polygons have **7744 neighbor connections**.\n-   S0: Sum of all weights in the matrix. The weights are **row-standardized (`W`)**, so each row sums to 1 → `S0 = 88`\n-   S1: Sum of **squared weights**\n-   S2: Sum of **squared sums of weights per row**\n    -   S1 and S2 are internal numbers used for calculating variance and significance in Moran’s I or Geary’s C.\n:::\n\n## 4.3 Computing Local Moran’s I\n\nTo compute local Moran’s I, the [`local_moran()`](https://sfdep.josiahparry.com/reference/local_moran) function of **sfdep** will be used. It computes *Ii*values, given a set of *zi* values and a listw object providing neighbour weighting information for the polygon associated with the zi values.\n\n| Local Moran’s I Value | Meaning                                          |\n|-----------------------|--------------------------------------------------|\n| **Ii \\> 1**           | Positive & Strong clustering                     |\n| **0 \\< I_i \\< 1**     | Positive & Moderate positive clustering          |\n| **Ii ≈ 0**            | No spatial autocorrelation (random distribution) |\n| **Ii \\< 0**           | Negative spatial autocorrelation (outliers)      |\n\nThe code chunks below are used to compute local Moran’s I of *GDPPC2012* at the county level.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- wm_q %>% \n  mutate(local_moran = local_moran(\n    GDPPC, nb, wt, nsim = 99),\n         .before = 1) %>%\n  unnest(local_moran)\n```\n:::\n\n\n\n`local_moran()` function returns a matrix of values whose columns are:\n\n-   Ii: the local Moran’s I statistics\n-   E.Ii: the expectation of local moran statistic under the randomisation hypothesis\n-   Var.Ii: the variance of local moran statistic under the randomisation hypothesis\n-   Z.Ii:the standard deviate of local moran statistic\n-   Pr(): the p-value of local moran statistic\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nglimpse(lisa)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 88\nColumns: 21\n$ ii           <dbl> -1.468468e-03, 2.587817e-02, -1.198765e-02, 1.022468e-03,…\n$ eii          <dbl> 2.239949e-03, 7.357741e-03, -2.276138e-02, 2.113699e-05, …\n$ var_ii       <dbl> 4.192853e-04, 8.167525e-03, 1.069188e-01, 5.763497e-06, 1…\n$ z_ii         <dbl> -0.181106344, 0.204930150, 0.032948774, 0.417094523, 0.51…\n$ p_ii         <dbl> 0.8562841049, 0.8376266986, 0.9737154375, 0.6766092708, 0…\n$ p_ii_sim     <dbl> 0.86, 1.00, 0.78, 0.66, 0.58, 0.70, 0.08, 0.14, 0.04, 0.1…\n$ p_folded_sim <dbl> 0.43, 0.50, 0.39, 0.33, 0.29, 0.35, 0.04, 0.07, 0.02, 0.0…\n$ skewness     <dbl> -0.7051429, -0.6513071, 0.9394877, 0.7189413, 0.6476455, …\n$ kurtosis     <dbl> 0.15983550, 0.27939794, 0.65047800, -0.27697090, -0.76801…\n$ mean         <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ median       <fct> High-High, High-High, High-High, High-High, High-High, Hi…\n$ pysal        <fct> Low-High, Low-Low, High-Low, High-High, High-High, High-L…\n$ nb           <nb> <2, 3, 4, 57, 85>, <1, 57, 58, 78, 85>, <1, 4, 5, 85>, <1,…\n$ wt           <list> <0.2, 0.2, 0.2, 0.2, 0.2>, <0.2, 0.2, 0.2, 0.2, 0.2>, <0…\n$ NAME_2       <chr> \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"Changde\", \"C…\n$ ID_3         <int> 21098, 21100, 21101, 21102, 21103, 21104, 21109, 21110, 2…\n$ NAME_3       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ ENGTYPE_3    <chr> \"County\", \"County\", \"County City\", \"County\", \"County\", \"C…\n$ County       <chr> \"Anxiang\", \"Hanshou\", \"Jinshi\", \"Li\", \"Linli\", \"Shimen\", …\n$ GDPPC        <dbl> 23667, 20981, 34592, 24473, 25554, 27137, 63118, 62202, 7…\n$ geometry     <POLYGON [m]> POLYGON ((22320.48 3301894,..., POLYGON ((35522.9…\n```\n\n\n:::\n:::\n\n\n\n### 4.3.1 Mapping local Moran’s I values\n\nUsing choropleth mapping functions of **tmap** package, we can plot the local Moran’s I values by using the code chinks below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nii.map <- tm_shape(lisa) +\n  tm_polygons(fill = \"ii\",\n              fill.scale = tm_scale_intervals(\n                style = \"pretty\",\n                n = 5,\n                values = \"brewer.RdBu\"),\n              fill.legend = tm_legend(\n                title = \"Local Morans'I\")) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_text(\"NAME_3\", size=0.6)+\n  tm_title(\"Loal Morans'I of GDPPC (Queen's method)\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"),\n    bg.color = \"#f6f6f6\",\n    frame = FALSE)\nii.map\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-12-1.png){width=1152}\n:::\n:::\n\n\n\n### 4.3.2 Mapping local Moran’s I p-values\n\nThe choropleth shows there is evidence for both positive and negative Ii values. However, it is useful to consider the p-values for each of these values, as consider above.\n\nThe code chunks below produce a choropleth map of Moran’s I p-values by using functions of **tmap** package.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_ii.map <- tm_shape(lisa) +\ntm_polygons(fill = \"p_ii\", \n              fill.scale = tm_scale_intervals(\n                breaks = c(-Inf, 0.001, 0.01, 0.05, 0.1, Inf),\n                values = \"-brewer.Reds\"),\n              fill.legend = tm_legend(\n                title = \"p-value\")) + \n  tm_borders(fill_alpha = 0.5) +\n  tm_text(\"NAME_3\", size=0.6)+\n  tm_title(\"P-values of Loal Moran's I of GDPPC (Queen's method)\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_layout(\n    legend.position = c(\"left\", \"bottom\"),\n    bg.color = \"#f6f6f6\",\n    frame = FALSE)\n  \np_ii.map\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-13-1.png){width=1152}\n:::\n:::\n\n\n\n### 4.3.3 Mapping both local Moran’s I values and p-values\n\nFor effective interpretation, it is better to plot both the local Moran’s I values map and its corresponding p-values map next to each other.\n\nThe code chunk below will be used to create such visualisation.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmap_arrange(ii.map, p_ii.map, asp=1, ncol=2)\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-14-1.png){width=1152}\n:::\n:::\n\n\n\n::: callout-note\n## Result Interpretation\n\n-   **Hot Spots (High-High clusters):** Counties includingChangsha, Wangcheng and Liuyang in the eastern region form a prominent high-high cluster with high Local Moran's I values (3-5) and statistically significant p-values. This cluster represents an economic agglomeration where high-GDPPC counties are spatially concentrated, likely benefiting from urban spillover effects and economic synergies.\n\n-   **Cold Spots (Low-Low Clusters):** Counties including Longhui and Wugang in the western region form a low-low cluster, with low Local Moran's I values (0-1) and statistically significant p-values. This pattern indicates a concentration of economically disadvantaged areas, suggesting regional disparities and potential geographic barriers to economic development in the western part of the province.\n\n-   **Outliers (Low-High):** Counties includes Taojiang & PingJiang in the east region and with negative Local Moran's I values (-2 to -1), indicating spatial outliers. These areas have significantly lower GDPPC compared to their neighbors, representing low-high outliers that stand in stark contrast to the surrounding higher-performing counties. It suggests potential economic shadow effects where nearby high-growth areas may be drawing away skilled labor, investment or resources, creating relative economic disadvantages in neighboring regions.\n:::\n\n## 4.4 Preparing and Visualising LISA Map\n\nVisualizing LISA involves creating maps that highlight significant spatial patterns, such as hot spots (high values clustered together) and cold spots (low values clustered together), as well as identifying spatial outliers. Common methods include choropleth maps showing LISA values, Moran scatterplots which depict local spatial autocorrelation for individual locations, and hot spot analysis maps.\n\nThe LISA Cluster Map shows the significant locations color coded by type of spatial autocorrelation. The first step before we can generate the LISA cluster map is to plot the Moran scatterplot.\n\n### 4.4.1 Plotting Moran scatterplot\n\nA Moran Scatterplot is a graphical tool in spatial analysis that visualizes the relationship between a variable’s values and the average values of its neighboring locations (its spatial lag) to identify spatial autocorrelation. By plotting standardized values of the variable on the x-axis and its spatial lag on the y-axis, the plot’s slope represents Moran’s I, revealing patterns of high-high or low-low value clusters and high-low or low-high value outliers.\n\nIn the code chunk below, [`st_lag()`](https://sfdep.josiahparry.com/reference/st_lag) of **sfdep** package is used to calculates the spatial lag of GDPPC given a neighbor (i.e. nb) and weights list (i.e. wt).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(lag_GDPPC = st_lag(\n    GDPPC, nb, wt),\n    .before = 1) %>%\n  unnest(lag_GDPPC)\n```\n:::\n\n\n\nThen, the code chunk below is used to plot the Moran Scatterplot of GDPPC against its spatial lag version as shown in the code cunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = GDPPC, \n           y = lag_GDPPC)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"red\") +\n  geom_text_repel(aes(label = County),\n                  size = 3,\n                  max.overlaps = 5)+\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Local Moran's I Scatterplot\") +\n  theme_minimal()+\n  theme(plot.title = element_text(size = 12),\n        plot.background = element_rect(fill = \"#f6f6f6\",color = NA),\n        panel.background = element_rect(fill = \"#f6f6f6\",color = NA))\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\nThe Moran Scatterplot above is not very intuitive. To support effective visual communication, the code chunk below is used.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = GDPPC, \n           y = lag_GDPPC, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_text_repel(aes(label = County),\n                  size = 3,\n                  max.overlaps = 10)+\n  geom_hline(yintercept=mean(lisa$lag_GDPPC), lty=2) + \n  geom_vline(xintercept=mean(lisa$GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"GDPPC\",\n       y = \"Spatial Lag of GDPPC\",\n       title = \"Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()+\n  theme(plot.title = element_text(size = 12),\n        plot.background = element_rect(fill = \"#f6f6f6\",color = NA),\n        panel.background = element_rect(fill = \"#f6f6f6\",color = NA))\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\nNotice that the plot is split in 4 quadrants. The top right corner belongs to areas that have high GDPPC and are surrounded by other areas that have the average level of GDPPC. This are the high-high locations in the lesson slide.\n\n### 4.4.2 Plotting Moran scatterplot with standardised variable\n\nFirst we will use [*scale()*](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/scale) to centers and scales the variable. Here centering is done by subtracting the mean (omitting NAs) the corresponding columns, and scaling is done by dividing the (centered) variable by their standard deviations.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(z_GDPPC = scale(GDPPC),\n         z_lag_GDPPC = scale(lag_GDPPC),\n         .before = 1)\n```\n:::\n\n\n\nThe [*as.vector()*](https://www.rdocumentation.org/packages/pbdDMAT/versions/0.5-1/topics/as.vector) added to the end is to make sure that the data type we get out of this is a vector, that map neatly into out dataframe.\n\nNow, we are ready to plot the Moran scatterplot again by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = lisa, \n       aes(x = z_GDPPC, \n           y = z_lag_GDPPC, \n           color = mean)) +\n  geom_point(size = 2) +\n  geom_smooth(method = \"lm\", \n              se = FALSE, \n              color = \"black\") +\n  geom_text_repel(aes(label = County),\n                  size = 3,\n                  max.overlaps = 10)+  \n  geom_hline(yintercept=mean(lisa$z_lag_GDPPC), lty=2) + \n  geom_vline(xintercept=mean(lisa$z_GDPPC), lty=2) +\n  scale_color_manual(\n    values = c(\"High-High\" = \"red\", \n               \"Low-Low\" = \"blue\",\n               \"Low-High\" = \"lightblue\", \n               \"High-Low\" = \"pink\")) +\n  labs(x = \"Standardised GDPPC\",\n       y = \"Standardised Spatial Lag of GDPPC\",\n       title = \"Standardised Moran Scatterplot with LISA Quadrants\") +\n  theme_minimal()+\n  theme(plot.title = element_text(size = 12),\n        plot.background = element_rect(fill = \"#f6f6f6\",color = NA),\n        panel.background = element_rect(fill = \"#f6f6f6\",color = NA))  \n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n### 4.4.3 Preparing LISA map classes\n\nThe code chunks below show the steps to prepare a LISA cluster map.\n\nNext, derives the spatially lagged variable of interest (i.e. GDPPC) and centers the spatially lagged variable around its mean.\n\nThis is follow by centering the local Moran’s around the mean.\n\nNext, we will set a statistical significance level for the local Moran.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsignif <- 0.05       \n```\n:::\n\n\n\n### 4.4.4 Plotting and visualising LISA map\n\nBy default, the LISA classes are stored in *mean*, *median* and *pysal* fields of lisa sf data frame. To prepare the LISA map, we will derive a new field called LISA-cluster from either one of these three field by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa <- lisa %>%\n  mutate(\n    LISA_cluster = ifelse(\n      p_ii < 0.05,\n      as.character(mean), \n      \"Insignificant\"),\n    LISA_cluster = factor(\n      LISA_cluster,\n      levels = c(\"Insignificant\", \"Low-Low\", \"Low-High\", \"High-Low\", \"High-High\") # by mean value\n    )\n  )\n```\n:::\n\n\n\nNotice that a new class called *Insignificant* has been added for records whereby p_ii \\> 0.05.\n\nNow, we can plot the LISA map by using the code chunk below.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlisa_map <- tm_shape(lisa) + \n  tm_polygons(\n    fill = \"LISA_cluster\",\n    fill.scale = tm_scale_categorical(\n      values = c(\n        \"grey80\",      # Insignificant\n        \"blue\",        # Low-Low\n        \"lightblue\",   # Low-High\n        \"pink\",        # High-Low\n        \"red\"          # High-High\n      )\n    ),\n    fill.legend = tm_legend(\n      title = \"LISA Cluster\",\n      position = tm_pos_in(\"left\", \"bottom\"))\n  ) +\n  tm_text(\"NAME_3\", size=0.6)+\n  tm_title(\"Local Moran's I Clusters (p < 0.05)\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_layout(\n    bg.color = \"#f6f6f6\",\n    frame = FALSE)\nlisa_map\n```\n\n::: {.cell-output-display}\n![](Hands-on-Ex05.b_files/figure-html/unnamed-chunk-22-1.png){width=1152}\n:::\n:::\n\n\n\n# 5 Reference\n\n-   Kam, T.S. (2025). [Local Measures of Spatial Autocorrelation](https://r4gdsa.netlify.app/chap10)\n",
    "supporting": [
      "Hands-on-Ex05.b_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}