project:
  type: website
  
website:
  title: "ISSS626 GAAxJH"
  page-footer:
    center:
       © 2025 Johsuan Huang ʕ•ᴥ•ʔ | Site built with [Quarto](https://quarto.org) | Hosted on [Netlify](https://www.netlify.com/)
  favicon: images/favicon/favicon-96x96.png
  page-navigation: true
  navbar: 
    logo: images/Logo2.png
    title: false
    collapse-below: lg
    search: true
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on 1.a: Geospatial Data Science with R"
            href: Hands-on/Hands-on-Ex01/Hands-on-Ex01_a.html
          - text: "Hands-on 1.b: Thematic Mapping and GeoVisualisation with R"
            href: Hands-on/Hands-on-Ex01/Hands-on-Ex01_b.html
          - text: "Hands-on 2.a: 1st Order Spatial Point Patterns Analysis Methods"
            href: Hands-on/Hands-on-Ex02/Hands-on-Ex02_a.html
          - text: "Hands-on 2.b: 2nd Order Spatial Point Patterns Analysis Methods"
            href: Hands-on/Hands-on-Ex02/Hands-on-Ex02_b.html  
          - text: "Hands-on 3: Spatio-Temporal Point Patterns Analysis"
            href: Hands-on/Hands-on-Ex03/Hands-on-Ex03.html  
          - text: "Hands-on 4: Spatial Weights and Applications"
            href: Hands-on/Hands-on-Ex04/Hands-on-Ex04.html       
          - text: "Hands-on 5.a: Global Measures of Spatial Autocorrelation"
            href: Hands-on/Hands-on-Ex05/Hands-on-Ex05.a.html
          - text: "Hands-on 5.b: Local Measures of Spatial Autocorrelationn"
            href: Hands-on/Hands-on-Ex05/Hands-on-Ex05.b.html
          - text: "Hands-on 6: Geographical Segmentation with Spatially Constrained Clustering Techniques"
            href: Hands-on/Hands-on-Ex06/Hands-on-Ex06.html

      - text: "In-class Exercises"
        menu:
          - text: "In-class 3.a"
            href: In-class/In-class-Ex03/In-class_Ex03a.html
          - text: "In-class 3.b"
            href: In-class/In-class-Ex03/In-class_Ex03b.html
          - text: "In-class 4"
            href: In-class/In-class-Ex04/In-class_Ex04.html
          - text: "In-class 5"
            href: In-class/In-class-Ex05/In-class_Ex05.html
          - text: "In-class 6"
            href: In-class/In-class-Ex06/In-class-Ex06.html
      - text: "Take-home Exercises"
        menu:
          - text: "Take-home Ex01: Geospatial Analytics for Public Good"
            href: Take-home/Take-home-Ex1/Take-home_Ex01.html
            
    right:
      - href: about.qmd
        text: About
      
format:
  html:
    toc: true
    toc-location: right
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap

editor: visual