project:
  type: website
  
website:
  title: "ISSS626 GAAxJH"
  page-footer:
    center:
       © 2025 Johsuan Huang ʕ•ᴥ•ʔ | Site built with [Quarto](https://quarto.org) | Hosted on [Netlify](https://www.netlify.com/)
  favicon: images/favicon/favicon-96x96.png
  page-navigation: true
  navbar: 
    logo: images/Logo2.png
    title: false
    collapse-below: lg
    search: true
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on 1.a: Geospatial Data Science with R"
            href: Hands-on/Hands-on-Ex01/Hands-on-Ex01_a.html
          - text: "Hands-on 1.b: Thematic Mapping and GeoVisualisation with R"
            href: Hands-on/Hands-on-Ex01/Hands-on-Ex01_b.html           
      - text: "In-class Exercises"
        menu:
          - text: "In-class 1"
              
      - text: "Take-home Exercises"
        menu:
          - text: "Take-home 1"
            
    right:
      - href: about.qmd
        text: About
      
format:
  html:
    toc: true
    toc-location: right
    theme: 
      - theme.scss
    highlight-style: tango
    code-copy: hover
    code-overflow: wrap

editor: visual