{
  "hash": "f55b955a9c96026bc41f1ddb4828a680",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Ex01: Geospatial Analytics for Public Good\"\nauthor: Huang Johsuan\ndate: \"September 18, 2025\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1 Overview\n\nThe locations of businesses and firms are central to urban development, influencing economic growth, job creation, and the availability of resources and services for residents and other businesses. Strategic locations provide competitive advantages, access to talent and infrastructure, and impact brand image and market positioning, while also shaping the city’s overall character and functionality by fostering specialized districts and facilitating efficient supply chains and employee commutes.\n\nStudying the spatio-temporal patterns of businesses and firms is crucial for urban development because it reveals how economic activity and urban forms evolve, enabling better urban planning, promoting sustainability, identifying urban inefficiencies, and enhancing quality of life. By understanding where and when businesses locate and operate, urban planners can design cities more effectively, anticipate growth, ensure resource efficiency, and tailor infrastructure to support economic vitality and community well-being.\n\n## 1.1 Objectives\n\nIn this take-home exercise, we are interested to investigate the spatial and spatio-temporal patterns of new businesses and firms established in Singapore for the **first six months of 2025**\n\nThe specific objectives of this take-home exercise are as follows:\n\n-   To identify the “where” and “when” of new business entities, revealing clusters, patterns, and trends that are crucial for informed urban planning, resource allocation, and economic development.\n\n-   To identify complex interaction patterns and emergent phenomena in the distribution of new businesses beyond simple proximity or density, such as clustering of related businesses, the influence of past trends on future locations, and the overall structural development of commercial areas, which are crucial for scientific urban planning and policy-making.\n\nBy understanding where businesses are located and how their distribution changes over time, urban planners and managers can unlock spatial intelligence, optimize operations, and create effective strategies to attract investment and promote sustainable growth.\n\n## 1.2 Rationale for Industry Selection\n\nThis analysis explores the business distribution patterns of three key sectors: 56112 cafes, 471 non-specialized retail stores and 663 family offices. These industries are selected for the following reasons:\n\n### 1.2.1 Cafes (SSIC:56112)\n\nKopitiam culture is deeply ingrained in Singapore's social fabric and remains highly popular. This makes it interesting to explore their location strategies, whether they prefer to open outlets near competitors to attract foot traffic or in areas with fewer rivals to reduce competition?\n\n### 1.2.2 Retail Sale in Non-specialised Stores (SSIC:471)\n\nSSIC 471 encompasses supermarkets, hypermarkets, convenience stores and other non-specialized retail stores. Although e-commerce market share continues to grow, I have noticed that various small retailers still operate in HDB estates and at street level. Hence, I am curious whether these stores are distributed as I expected - clustered in residential areas over time.\n\n### 1.2.3 Fund Management Activities (SSIC:663)\n\nIn recent years, many investors have been shifting their assets from Hong Kong and Shanghai to Singapore. Based on news reports, many of them have established family offices to manage their wealth. Therefore, I am curious about where these companies choose to register their operations. Are they clustered in the Central Business District as expected?\n\n# 2 Getting Started\n\n## 2.1 Import Libraries\n\nThis analysis uses the following libraries:\n\n| Library | Desc |\n|------------------------------------|------------------------------------|\n| [**sf**](https://r-spatial.github.io/sf/) | handling geospatial data |\n| [**tmap**](https://cran.r-project.org/web/packages/tmap/index.html) | visualization for geospatial data |\n| **tidyverse** | handling data including packages **readr**, **tidyr and dplyr** |\n| [**sparr**](https://tilmandavies.github.io/sparr/index.html) | provides functions to estimate fixed and adaptive kernel-smoothed spatial relative risk surfaces via the density-ratio method and perform subsequent inference.  |\n| [**spatstat**](https://spatstat.org/) | for point pattern analysis |\n| [**terra**](https://rspatial.github.io/terra/index.html) | a modern spatial data analysis package to replace the raster package. terra provides functionalities for creating, reading, manipulating, and writing raster and vector data, and it’s built on top of GDAL and PROJ libraries for enhanced performance |\n| rvest | scraping (or harvesting) data from web pages |\n| knitr | generate elegant, flexible, and fast dynamic report |\n| httr | package in R provides a set of tools for interacting with web resources via HTTP. It simplifies the process of making HTTP requests (GET, POST, PUT, DELETE, etc.) and handling the responses |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf,tmap,tidyverse,sparr,terra,spatstat,rvest,httr,knitr)\n```\n:::\n\n\n\n## 2.2 Import Master Plan 2019 Data\n\n**Master Plan 2019** is the statutory land use plan that guides Singapore's development in the medium term over the next 10 to 15 years. It is available as a polygon feature layer in **KML** format, maintained and published by the Urban Redevelopment Authority (URA)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- st_read(\"data/geospatial/MasterPlan2019PlanningAreaBoundaryNoSea.kml\")\n```\n:::\n\n\n\nTo extract the information, the function from Hands-on Ex01.b is resued to extract data from html:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nextract_kml_field <- function(html_text, field_name) {\n  if (is.na(html_text) || html_text == \"\") return(NA_character_) # check if text is na\n  \n  page <- read_html(html_text)\n  rows <- page %>% html_elements(\"tr\") # find table row element \n  \n  value <- rows %>%\n    # looks through each row to find table header == field_name and\n    keep(~ html_text2(html_element(.x, \"th\")) == field_name) %>% \n    html_element(\"td\") %>% # extract table data\n    html_text2() # and then extract clean text context\n  \n  if (length(value) == 0) NA_character_ else value # return value if is not NA\n}\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- mppa %>%\n  mutate(REGION_N = map_chr(Description,extract_kml_field,\"REGION_N\"),\n         PLN_AREA_N = map_chr(Description,extract_kml_field,\"PLN_AREA_N\"))%>%\n  select(-Name, -Description) %>% # unselect columns \"Name\" and \"Description\"\n  relocate(geometry, .after = last_col()) # move the \"geometry\" to the end\n```\n:::\n\n\n\nFollowing data extraction, let us transform its CRS from WGS84 to SVY21 for accuracy and further spatial analysis requirements:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- mppa %>%\n    #Removes Z (elevation) and M (measure) dimensions from the geometry if they exist\n  st_zm(drop = TRUE, what = \"ZM\") %>% \n  st_transform(crs = 3414)\nst_geometry(mppa)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nwrite_rds(mppa,\"data/rds/mppa.rds\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa <- read_rds(\"data/rds/mppa.rds\")\n```\n:::\n\n\n\nLet us plot planning area:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa) +\n  tm_polygons(col =\"REGION_N\",\n      palette = \"set2\",\n              lwd = 0.5)+\n   tm_text(\"PLN_AREA_N\", size=0.4,\n           auto.placement = TRUE,\n           remove.overlap = TRUE)+\n  tm_title(\"Planning Area in Singapore\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-8-1.png){width=1152}\n:::\n:::\n\n\n\nSince our focus is on business operations occurring on the main island, this study will exclude non-business areas such as the North-Eastern Islands, Western Islands, Southern Islands, Central Water Catchment and Western Water Catchment.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmppa_sf <- mppa %>%\n  filter (PLN_AREA_N != \"CENTRAL WATER CATCHMENT\",\n          PLN_AREA_N != \"WESTERN WATER CATCHMENT\",\n         PLN_AREA_N != \"WESTERN ISLANDS\",\n         PLN_AREA_N != \"SOUTHERN ISLANDS\",\n         PLN_AREA_N != \"NORTH-EASTERN ISLANDS\",\n         )\n```\n:::\n\n\n\nLet's plot our study area again:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n  tm_polygons(col =\"REGION_N\",\n      palette = \"set2\",\n              lwd = 0.5)+\n   tm_text(\"PLN_AREA_N\", size=0.4,\n           auto.placement = TRUE,\n           remove.overlap = TRUE)+\n  tm_title(\"Subzones in Singapore\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-10-1.png){width=1152}\n:::\n:::\n\n\n\n## 2.3 Import ACRA Data\n\nThe data from the Accounting and Corporate Regulatory Authority (ACRA) will be used for spatial analysis. The dataset comprises 27 files organized by the first letter of the company name (A-Z and Others). The data encompasses information on all businesses registered in Singapore, including company profiles, industry classifications, and registration details.\n\nSince the data files follow a consistent naming format and are stored in the same folder, we will use `map_dfr()` to import and combine all files:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfolder_path <- \"data/ACRA\"\nfile_list <- list.files(path = folder_path,\n                        pattern = \"^ACRA*.*\\\\.csv$\",\n                        full.names = TRUE)\nacra <- file_list %>%\n  map_dfr(read_csv)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## 2.4 Extract Selected Industry Data\n\nIn this section, we will extract selected data from January to June 2025 for three industries: Cafes (SSIC 56112), Non-specialised Retail (SSIC 471), and Fund Management (SSIC 663).\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafes_56112 <- acra %>%\n  select(1,3,4,8:9,11,17,22) %>%\n  filter(grepl(\"56112\", primary_ssic_code)) %>% \n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         Year = year(date),\n         Month_num = month(date,\n                           label =TRUE,\n                           abbr =TRUE)) %>%\n  # make sure the post_code are 6 digits\n  mutate(postal_code = str_pad(postal_code,\n                               width =6,\n                               side = \"left\",pad =\"0\"))  %>% \n  filter(Year == 2025,\n         Month_num %in% c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\"))\n\nretail_471 <- acra %>%\n  select(1,3,4,8:9,11,17,22) %>%\n  filter(grepl(\"^471\", primary_ssic_code)) %>% \n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         Year = year(date),\n         Month_num = month(date,\n                           label =TRUE,\n                           abbr =TRUE)) %>%\n  # make sure the post_code are 6 digits\n  mutate(postal_code = str_pad(postal_code,\n                               width =6,\n                               side = \"left\",pad =\"0\"))  %>% \n  filter(Year == 2025,\n         Month_num %in% c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\"))\n\nFM_663 <- acra %>%\n  select(1,3,4,8:9,11,17,22) %>%\n  filter(grepl(\"^663\", primary_ssic_code)) %>% \n  rename(date = registration_incorporation_date) %>%\n  mutate(date = as.Date(date),\n         Year = year(date),\n         Month_num = month(date,\n                           label =TRUE,\n                           abbr =TRUE)) %>%\n  # make sure the post_code are 6 digits\n  mutate(postal_code = str_pad(postal_code,\n                               width =6,\n                               side = \"left\",pad =\"0\"))  %>% \n  filter(Year == 2025,\n         Month_num %in% c(\"Jan\",\"Feb\",\"Mar\",\"Apr\",\"May\",\"Jun\"))\n```\n:::\n\n\n\n## 2.5 Geocoding for Coodinates\n\nInstead of coordinates, ACRA only provides postal code and address. To retrieve the coordinates, we need to apply geocoding on postal codes using OneMap API.\n\nFirstly, we combine the extracted data by row:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncombined_data <- rbind(cafes_56112,retail_471,FM_663)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\nNext, we extract the unique postal codes from the combined data.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npostcodes <- unique(combined_data$postal_code)\nlength(postcodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 595\n```\n\n\n:::\n:::\n\n\n\nWe have total 595 unique observations in this exercise.\n\nNext, we use the `httr` package to send a GET request to the OneMap API for coordinate retrieval:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://onemap.gov.sg/api/common/elastic/search\"\n\nfound <- data.frame()\nnot_found <- data.frame(postcode =character())\n\nfor(pc in postcodes) {\n  query <- list(\n    searchVal = pc,\n    returnGeom = \"Y\",\n    getAddrDetails = \"Y\",\n    pageNum =\"1\"\n  )\n  \n  res <- GET(url, query=query)\n  json <- content(res)\n  \n  if(json$found !=0) {\n    df <- as.data.frame(json$results, stringFactors =FALSE)\n    df$input_postcode <- pc\n    found <- bind_rows(found,df)\n  } else{\n    not_found <- bind_rows(not_found, data.frame(postcode=pc))\n  }\n}\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\nNow, let us examine the mapping result:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(found)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 595\n```\n\n\n:::\n\n```{.r .cell-code}\nnrow(not_found)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n\nThe results above indicate we successfully retrieve all the coordinates !\n\n## 2.6 Combine and Convert Data into sf Format\n\nIn this section, we apply `left_join()` to merge the original dataset with the geocoded results containing spatial coordinates. Using the retrieved X and Y values (longitude and latitude) as coordinates, we convert the combined dataset into an `sf` object with `st_as_sf()`.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfound <- found %>% select(1:10)\n\n# cafe\ncafes_56112 <- cafes_56112 %>%\n  left_join(found,\n            by = c('postal_code'='POSTAL'))\n\ncafe_sf <- st_as_sf(cafes_56112,\n                         coords = c(\"X\",\"Y\"),\n                         crs=3414)\n\n# retail\nretail_471 <- retail_471 %>%\n  left_join(found,\n            by = c('postal_code'='POSTAL'))\nretail_sf <- st_as_sf(retail_471,\n                         coords = c(\"X\",\"Y\"),\n                         crs=3414)\n\n# FM\nFM_663 <- FM_663 %>%\n  left_join(found,\n            by = c('postal_code'='POSTAL'))\nfm_sf <- st_as_sf(FM_663,\n                         coords = c(\"X\",\"Y\"),\n                         crs=3414)\n```\n:::\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n:::\n\n\n\n## 2.7 Mapping Geospatial Data\n\nAfter data preparation, let's plot the map and examine the distribution of the three industries:\n\n### 2.7.1 Cafes\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(cafe_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 167 features \nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 12020.59 ymin: 28485.43 xmax: 42416.59 ymax: 47897.38\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n    tm_polygons(col =\"REGION_N\",\n                border.col = \"white\",\n      palette = \"set2\",\n              lwd = 0.5)+\ntm_shape(cafe_sf) +\n  tm_dots(fill = \"black\", size = 0.5, shape = 16)+\n  tm_title(\"Cafe Distribution: H1 2025\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-25-1.png){width=1152}\n:::\n:::\n\n\n\nThere are 167 cafes (drink stores/stalls) opened from January 2025 to June 2025. Aside from the central region, their distribution appears relatively even across other areas.\n\n### 2.7.2 Non-specialised Retail Stores\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(retail_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 460 features \nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 4670.11 ymin: 27393.65 xmax: 45154.27 ymax: 49401.78\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n    tm_polygons(col =\"REGION_N\",\n                border.col = \"white\",\n      palette = \"set2\",\n              lwd = 0.5)+\ntm_shape(retail_sf) +\n  tm_dots(fill = \"black\", size = 0.5, shape = 17)+\n  tm_title(\"Non-specialized Retail Store Distribution: H1 2025\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-27-1.png){width=1152}\n:::\n:::\n\n\n\nA total of 460 non-specialised retail stores opened between January and June 2025. Compared to cafes, their distribution appears more clustered across all regions.\n\n### 2.7.3 Family Office\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_geometry(fm_sf)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGeometry set for 238 features \nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 12302.18 ymin: 27485.42 xmax: 42579.88 ymax: 48173.98\nProjected CRS: SVY21 / Singapore TM\nFirst 5 geometries:\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n    tm_polygons(col =\"REGION_N\",\n                border.col = \"white\",\n      palette = \"set2\",\n              lwd = 0.5)+\ntm_shape(fm_sf) +\n  tm_dots(fill = \"black\", size = 0.5, shape = 18)+\n  tm_title(\"Fund Management Activity Distribution: H1 2025\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-29-1.png){width=1152}\n:::\n:::\n\n\n\nA total of 238 family offices opened between January and June 2025. The family offices appear with high density concentrated in the CBD area.\n\n### 2.7.4 Combined Plot of the Three Industries’ Distribution\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mppa_sf) +\n    tm_polygons(col =\"REGION_N\",\n                border.col = \"white\",\n      palette = \"set2\",\n              lwd = 0.5)+\ntm_shape(retail_sf) +\n  tm_dots(fill = \"red\", size = 0.5, shape = 17)+    \ntm_shape(cafe_sf) +\n  tm_dots(fill = \"blue\", size = 0.5, shape = 16)+\ntm_shape(fm_sf) +\n  tm_dots(fill = \"black\", size = 0.5, shape = 18)+\n\n  tm_title(\"Fund Management Activity Distribution: H1 2025\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))+\n  tm_legend(frame = FALSE,\n            position = c(\"right\", \"bottom\"))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-30-1.png){width=1152}\n:::\n:::\n\n\n\nAmong the three industries, family offices exhibit the highest spatial intensity, with clear clusters concentrated in the CBD area.\n\n# 3 Geospatial Data wrangling\n\nSince the spatstat package relies on specific data structures like **ppp** (planar point pattern) for point data and **owin** for observation windows, we need to convert sf (Simple Features) objects into ppp and owin object.\n\n## 3.1 Converting sf data frames to ppp class\n\nThe code chunk below uses `as.ppp()` of **spatstat** package to convert data from sf format to ppp format:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafe_ppp <- as.ppp(cafe_sf)%>%\n          rjitter(retry = TRUE,\n          nsim = 1,\n          drop = TRUE)\nfm_ppp <- as.ppp(fm_sf)%>%\n          rjitter(retry = TRUE,\n          nsim = 1,\n          drop = TRUE)\nretail_ppp <- as.ppp(retail_sf)%>%\n          rjitter(retry = TRUE,\n          nsim = 1,\n          drop = TRUE)\n```\n:::\n\n\n\n## 3.2 Creating owin object\n\nIn **spatstat**, an object called ***owin*** is specially designed to represent this **polygonal region**. We need to use owin object to define the study area of the analysis:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsg_owin <- as.owin(mppa_sf)\n```\n:::\n\n\n\nThe study area look like this\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(sg_owin)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-33-1.png){width=1152}\n:::\n:::\n\n\n\n## **5.3 Combining point events object and owin object**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafeSG_ppp <- cafe_ppp[sg_owin]\nretailSG_ppp <- retail_ppp[sg_owin]\nfmSG_ppp <- fm_ppp[sg_owin]\n```\n:::\n\n\n\nExamine the output for three ppp objects:\n\n::: panel-tabset\n## Cafes\n\nA point is dropped outside the study area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafeSG_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 166 points\nMark variables: \n   uen entity_name entity_type_description entity_status_description date \naddress_type postal_code primary_ssic_code Year Month_num SEARCHVAL BLK_NO \nROAD_NAME BUILDING ADDRESS LATITUDE LONGITUDE\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n## Retail Stores\n\nAll points are within the study area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nretailSG_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 460 points\nMark variables: \n   uen entity_name entity_type_description entity_status_description date \naddress_type postal_code primary_ssic_code Year Month_num SEARCHVAL BLK_NO \nROAD_NAME BUILDING ADDRESS LATITUDE LONGITUDE\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n\n## Family Office\n\nAll points are within the study area\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfmSG_ppp\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMarked planar point pattern: 238 points\nMark variables: \n   uen entity_name entity_type_description entity_status_description date \naddress_type postal_code primary_ssic_code Year Month_num SEARCHVAL BLK_NO \nROAD_NAME BUILDING ADDRESS LATITUDE LONGITUDE\nwindow: polygonal boundary\nenclosing rectangle: [2667.54, 55941.94] x [21448.47, 50256.33] units\n```\n\n\n:::\n:::\n\n\n:::\n\n# 4 Cafes Spatial Point Pattern Analysis\n\nProblem Statement: Whether they prefer to open outlets near competitors to attract foot traffic or in areas with fewer rivals to reduce competition?\n\n## 4.1 **First-Order Spatial Point Patterns Analysis**\n\n### 4.1.1 Clark-Evan Test\n\nWe first perform the Clark-Evans test for **first-order spatial point pattern analysis** to determine whether the spatial point pattern of cafes exhibits clustering. Since we only have 167 points, it would be more robust to use Monte Carlo method instead of Z-test.\n\nThe hypothesis and alpha value are as follows:\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The distribution of cafes are randomly distributed (R=1)\n-   H1= The distribution of cafes are clustered (R\\<1)\n\n**Significance Level:** A 95% confidence level will be used (α = 0.05)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(cafeSG_ppp,\n                correction = \"none\",\n                clipregion = \"sg_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 99 simulations of CSR with fixed n\n\ndata:  cafeSG_ppp\nR = 0.5775, p-value = 0.01\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n## Result Interpretation\n\nBased on the Clark and Evans Test result, the R value is 0.59, with statistically siginificant p-value (p \\< 0.05). This provides sufficient evidence to reject the null hypothesis of Complete Spatial Randomness (CSR).\n\nTherefore, we conclude that newly opened cafes in Singapore exhibit a clustered spatial pattern. This suggests that cafes may tend to locate near one another, possibly due to shared preferences for high-footfall areas.\n:::\n\n### 4.1.2 **Kernel Density Estimation**\n\nAfter confirming the clustered pattern, let us apply the KDE method to visualize hotspots with high intensity.\n\nThe code below use `density()` functions with two automatic bandwidth methods: *bw.diggle* and *bw.ppl* and `adaptive.density()` funtions to perform KDE analysis:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafeSG_ppp_km <- rescale.ppp(\n  cafeSG_ppp, 1000, \"km\"\n)\n\nkde_cafeSG_km_ppl <- density(cafeSG_ppp_km,\n        sigma = bw.ppl,\n        edge = TRUE,\n        kernel = \"gaussian\")\n\nkde_cafeSG_km_dg <- density(cafeSG_ppp_km,\n        sigma = bw.diggle,\n        edge = TRUE,\n        kernel = \"gaussian\")\n\nkde_cafeSG_km_ad <- adaptive.density(cafeSG_ppp_km, \n  method=\"kernel\")\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg=\"#f6f6f6\",mfrow = c(2,2))\nplot(kde_cafeSG_km_dg, main = \"bw.diggle\")\nplot(kde_cafeSG_km_ppl, main = \"bw.ppl\")\nplot(kde_cafeSG_km_ad, main = \"bw.adaptive\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-40-1.png){width=1152}\n:::\n:::\n\n\n\nThe KDE plots above show high-density points around Bishan, Geylang and the Downtown Core, which are all located within the Central Region. Next, we zoom in on these three planning areas and reapply the Clark and Evans test as well as the KDE analysis\n\n## 4.2 **First-Order SPPA at the Planning Area Level**\n\n### 4.2.1 **Geospatial Data Wrangling**\n\nWe first extract the study area:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGL <- mppa_sf %>%\n  filter(PLN_AREA_N == \"GEYLANG\")\nDC <- mppa_sf %>%\n  filter(PLN_AREA_N == \"DOWNTOWN CORE\")\nBS <- mppa_sf %>%\n  filter(PLN_AREA_N == \"BISHAN\")\n```\n:::\n\n\n\nNext, create owin object:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGL_owin = as.owin(GL)\nDC_owin = as.owin(DC)\nBS_owin = as.owin(BS)\n```\n:::\n\n\n\nCombine ppp and owin object:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafe_GL_ppp = cafe_ppp[GL_owin]\ncafe_DC_ppp = cafe_ppp[DC_owin]\ncafe_BS_ppp = cafe_ppp[BS_owin]\n```\n:::\n\n\n\nLastly, rescale the ppp object:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafe_GL_ppp_km = rescale.ppp(cafe_GL_ppp,1000,\"km\")\ncafe_DC_ppp_km = rescale.ppp(cafe_DC_ppp,1000,\"km\")\ncafe_BS_ppp_km = rescale.ppp(cafe_BS_ppp,1000,\"km\")\n```\n:::\n\n\n\n### 4.2.2 Clark-Evan Test\n\nThe hypothesis and alpha value are the same as section 4.1:\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The distribution of cafes are randomly distributed (R=1)\n-   H1= The distribution of cafes are clustered (R\\<1)\n\n**Significance Level:** A 95% confidence level will be used (α = 0.05)\n\n::: panel-tabset\n## Geylang\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(cafe_GL_ppp,\n                correction = \"none\",\n                clipregion = \"GL_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  cafe_GL_ppp\nR = 0.76008, p-value = 0.013\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n## Downtown Core\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(cafe_DC_ppp,\n                correction = \"none\",\n                clipregion = \"DC_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  cafe_DC_ppp\nR = 0.55822, p-value = 0.001\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n\n## Bishan\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclarkevans.test(cafe_BS_ppp,\n                correction = \"none\",\n                clipregion = \"BS_owin\",\n                alternative = \"clustered\",\n                method = \"MonteCarlo\",\n                nsim=999)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tClark-Evans test\n\tNo edge correction\n\tMonte Carlo test based on 999 simulations of CSR with fixed n\n\ndata:  cafe_BS_ppp\nR = 0.64577, p-value = 0.002\nalternative hypothesis: clustered (R < 1)\n```\n\n\n:::\n:::\n\n\n:::\n\n::: callout-note\n## Result Interpretation\n\n1.  **Geylang**:\n\n    While the R value is 0.88, suggesting a clustered pattern, the p-value (0.06\\>0.05) indicates this clustered is not statistically significant, so we fail to reject the null hypothesis of Complete Spatial Randomness. Therefore, cafe locations in Geylanf **appear to follow a** **random spatial distribution pattern**.\n\n2.  **Downtown Core & Bishan:**\n\n    The R value of Downtown Core is 0.85 and Bishan is 0.58, with both statistically significant p-values (p \\< 0.05). This provides sufficient evidence to reject the null hypothesis of Complete Spatial Randomness, and conclude that the newly opened cafes in **Bishan and Downtown Core exhibit clustered spatial patterns**.\n:::\n\n### 4.2.3 **Kernel Density Estimation**\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg=\"#f6f6f6\",mfrow=c(1,3))\nplot(density(cafe_GL_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"Geylang\")\nplot(density(cafe_DC_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"Downtown Core\")\nplot(density(cafe_BS_ppp_km, \n             sigma=bw.diggle, \n             edge=TRUE, \n             kernel=\"gaussian\"),\n     main=\"Bishan\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-48-1.png){width=672}\n:::\n:::\n\n\n\nThe KDE plot shows that Bishan has a single dominant hotspot at its center, with a peak intensity of 150 density units per km². In contrast, the Downtown Core and Geylang feature multiple hotspots.\n\n## 4.3 **Second-Order Spatial Point Patterns Analysis**\n\nIn this section, Bishan and the Downtown Core are selected for second-order spatial point pattern analysis.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\n```\n:::\n\n\n\n### 4.3.1 Bishan Planning Area\n\n#### 4.3.1.1 **Compute G-function estimation**\n\nThe code below implement G-function to examine the nearest neighbor distance distribution :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_BS = Gest(cafe_BS_ppp, correction = \"border\")\npar(bg = \"#f6f6f6\")\nplot(G_BS, xlim=c(0,500))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-50-1.png){width=672}\n:::\n:::\n\n\n\n#### **4.3.1.2 Performing CSR Test**\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The nearest neighbor distances of cafes at Bishan are randomly distributed.\n-   H1= The nearest neighbor distances of cafes at Bishan are not randomly distributed\n\n**Significance Level:** A 98% confidence level will be used\n\nMonte Carlo test with G-fucntion:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_BS.csr <- envelope(cafe_BS_ppp, Gest,rank=1, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(G_BS.csr)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\n## Statistical Conclusion\n\nG(r) increases rapidly below 100m and remains above the upper confidence envelope, indicating that approximately 60% of cafes in Bishan have their nearest neighbor within 100m, which is significantly more than expected under spatial randomness.\n:::\n\n#### **4.4.1.3 Compute L-function estimation**\n\nThe code below implement L-function to examine the clustering at all scales:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_BS = Lest(cafe_BS_ppp, correction = \"Ripley\")\n\npar(bg = \"#f6f6f6\")\nplot(L_BS, . -r ~ r, \n     ylab= \"L(d)-r\", xlab = \"d(m)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-53-1.png){width=672}\n:::\n:::\n\n\n\n#### **4.4.1.4 Performing Complete Spatial Randomness Test**\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The distribution of cafes at Bishan are randomly distributed.\n-   H1= The distribution of childcare services at Bishan are not randomly distributed\n\n**Significance Level:** A 98% confidence level will be used\n\nMonte Carlo test with L-fucntion:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_BS.csr <- envelope(cafe_BS_ppp, Lest, nsim = 99, rank = 1, glocal=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(L_BS.csr, . - r ~ r, xlab=\"d\", ylab=\"L(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-55-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\n## Statistical Conclusion\n\nThis suggests Bishan has compact cafe clusters with a typical cluster diameter of 300-400m (radius 150-200m). Beyond this scale, the clustering effect gradually diminishes, but remains statisitically significant up to a of radius 700m.\n:::\n\n### 4.3.2 Downtown Core Planning Area\n\n#### 4.3.1.1 **Compute G-function estimation**\n\nThe code below implement G-function to examine the nearest neighbor distance distribution :\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_DC = Gest(cafe_DC_ppp, correction = \"border\")\npar(bg = \"#f6f6f6\")\nplot(G_DC, xlim=c(0,500))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-56-1.png){width=672}\n:::\n:::\n\n\n\n#### **4.3.3.2 Performing CSR Test**\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The nearest neighbor distances of cafes at Geylang are randomly distributed.\n-   H1= The nearest neighbor distances of cafes at Geylang are not randomly distributed\n\n**Significance Level:** A 98% confidence level will be used (α = 0.02)\n\nMonte Carlo test with G-fucntion:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nG_DC.csr <- envelope(cafe_DC_ppp, Gest,rank=1, nsim = 99)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(G_DC.csr)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-58-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\n## Statistical Conclusion\n\nG(r) shows that cafes distribution in Downtown Core follow a random pattern and has no clusters statistically.\n:::\n\n#### **4.3.3.3 Compute L-function estimation**\n\nThe code below implement L-function to examine the clustering at all scales:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_DC = Lest(cafe_DC_ppp, correction = \"Ripley\")\n\npar(bg = \"#f6f6f6\")\nplot(L_DC, . -r ~ r, \n     ylab= \"L(d)-r\", xlab = \"d(m)\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-59-1.png){width=672}\n:::\n:::\n\n\n\n#### **4.3.2.4 Performing Complete Spatial Randomness Test**\n\n**Null and Alternative Hypotheses:**\n\n-   H0 = The distribution of cafes at Downtown Core are randomly distributed.\n-   H1= The distribution of childcare services at Downtown Core are not randomly distributed\n\n**Significance Level:** A 98% confidence level will be used (α = 0.02)\n\nMonte Carlo test with L-fucntion:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nL_DC.csr <- envelope(cafe_DC_ppp, Lest, nsim = 99, rank = 1, glocal=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nGenerating 99 simulations of CSR  ...\n1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,\n21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,\n41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,\n61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,\n81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, \n99.\n\nDone.\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npar(bg = \"#f6f6f6\")\nplot(L_DC.csr, . - r ~ r, xlab=\"d\", ylab=\"L(d)-r\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex01_files/figure-html/unnamed-chunk-61-1.png){width=672}\n:::\n:::\n\n\n\n::: callout-note\n## Statistical Conclusion\n\nAlthough the obeserved L(d)-r is above 0, the values are not statistically significant. Hence, we conclude Downtown Core's cafe follows complete spatial randomness and no significant clusters in the area.\n:::\n\n#### 4.3.2.5 Summary\n\nInterestingly, while both Bishan and the Downtown Core exhibit R values below 1 in the first-order SPPA, which indicates clustering, and the KDE plots also show high point density within these planning areas, the second-order SPPA reveals a different pattern. Only Bishan demonstrates strong clustering at a radius of 150–200 m.\n\nThe list of business entities registered under the 'cafe' industry classification is as follows:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncafe_bishan <- cafe_sf %>% \n  filter(grepl(\"^57\", postal_code)) \nkable(cafe_bishan)\n```\n\n::: {.cell-output-display}\n\n\n|uen        |entity_name                |entity_type_description          |entity_status_description |date       |address_type |postal_code | primary_ssic_code| Year|Month_num |SEARCHVAL                         |BLK_NO |ROAD_NAME      |BUILDING                     |ADDRESS                                                        |LATITUDE         |LONGITUDE        |geometry                  |\n|:----------|:--------------------------|:--------------------------------|:-------------------------|:----------|:------------|:-----------|-----------------:|----:|:---------|:---------------------------------|:------|:--------------|:----------------------------|:--------------------------------------------------------------|:----------------|:----------------|:-------------------------|\n|202515476Z |BASTILLE PTE. LTD.         |Local Company                    |Live Company              |2025-04-10 |LOCAL        |576194      |             56112| 2025|Apr       |THE WINDSOR                       |5A     |ONTARIO AVENUE |THE WINDSOR                  |5A ONTARIO AVENUE THE WINDSOR SINGAPORE 576194                 |1.3564322659845  |103.827926805238 |POINT (27399.96 37612.9)  |\n|53503285D  |COFFEE NEAR ME             |Sole Proprietorship/ Partnership |Live                      |2025-04-30 |LOCAL        |574078      |             56112| 2025|Apr       |ISLAND COUNTRY VILLAS             |20     |CASUARINA WALK |ISLAND COUNTRY VILLAS        |20 CASUARINA WALK ISLAND COUNTRY VILLAS SINGAPORE 574078       |1.37576736358578 |103.826798673849 |POINT (27274.42 39750.88) |\n|202512498W |OTTIE DELICACY PTE. LTD.   |Local Company                    |Live Company              |2025-03-21 |LOCAL        |576147      |             56112| 2025|Mar       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202513235R |OTTIE FEAST PTE. LTD.      |Local Company                    |Live Company              |2025-03-26 |LOCAL        |576147      |             56112| 2025|Mar       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202513249M |OTTIE INDULGENCE PTE. LTD. |Local Company                    |Live Company              |2025-03-26 |LOCAL        |576147      |             56112| 2025|Mar       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202513264D |OTTIE TREATS PTE. LTD.     |Local Company                    |Live Company              |2025-03-26 |LOCAL        |576147      |             56112| 2025|Mar       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202518301K |OTTIE MOMENTS PTE. LTD.    |Local Company                    |Live Company              |2025-04-28 |LOCAL        |576147      |             56112| 2025|Apr       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202518327C |OTTIE SPARKS PTE. LTD.     |Local Company                    |Live Company              |2025-04-28 |LOCAL        |576147      |             56112| 2025|Apr       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202521992G |OTTIE BITES PTE. LTD.      |Local Company                    |Live Company              |2025-05-21 |LOCAL        |576147      |             56112| 2025|May       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202522003H |OTTIE CREATIONS PTE. LTD.  |Local Company                    |Live Company              |2025-05-21 |LOCAL        |576147      |             56112| 2025|May       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202522008D |OTTIE STYLES PTE. LTD.     |Local Company                    |Live Company              |2025-05-21 |LOCAL        |576147      |             56112| 2025|May       |LIP HING INDUSTRIAL BUILDING      |3      |PEMIMPIN DRIVE |LIP HING INDUSTRIAL BUILDING |3 PEMIMPIN DRIVE LIP HING INDUSTRIAL BUILDING SINGAPORE 576147 |1.35227568621676 |103.842338285452 |POINT (29003.79 37153.29) |\n|202522076K |TASTE IPOH PTE. LTD.       |Local Company                    |Live Company              |2025-05-21 |LOCAL        |573970      |             56112| 2025|May       |MIDVIEW CITY                      |24     |SIN MING LANE  |MIDVIEW CITY                 |24 SIN MING LANE MIDVIEW CITY SINGAPORE 573970                 |1.35902072145403 |103.833760733143 |POINT (28049.21 37899.12) |\n|202525543C |UNIQUEJ CAFE PTE. LTD.     |Local Company                    |Live Company              |2025-06-12 |LOCAL        |570022      |             56112| 2025|Jun       |22 SIN MING ROAD SINGAPORE 570022 |22     |SIN MING ROAD  |NIL                          |22 SIN MING ROAD SINGAPORE 570022                              |1.3572844410824  |103.839396679952 |POINT (28676.42 37707.13) |\n\n\n:::\n:::\n\n\n\nNotably, nine related companies are registered at the same location, which may have artificially inflated the clustering pattern observed. If these nine companies were considered as a single entity, it is likely that Bishan would no longer exhibit significant clustering.\n\n# 5 Non-Specialised Retail Store SPPA\n\n## 5.1 \n",
    "supporting": [
      "Take-home_Ex01_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}