{
  "hash": "2a4bf07f36dfbaecb1e508b0d4401c65",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Ex02: Geospatial Analytics for Public Good\"\nauthor: Huang Johsuan\ndate: \"2025/10/12\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n\n\n# 1 Set the Scene\n\nThe locations of businesses and firms are central to urban development, influencing economic growth, job creation, and the availability of resources and services for residents and other businesses. Strategic locations provide competitive advantages, access to talent and infrastructure, and impact brand image and market positioning, while also shaping the city’s overall character and functionality by fostering specialized districts and facilitating efficient supply chains and employee commutes.\n\nStudying the spatio-temporal patterns of businesses and firms is crucial for urban development because it reveals how economic activity and urban forms evolve, enabling better urban planning, promoting sustainability, identifying urban inefficiencies, and enhancing quality of life. By understanding where and when businesses locate and operate, urban planners can design cities more effectively, anticipate growth, ensure resource efficiency, and tailor infrastructure to support economic vitality and community well-being.\n\n# 2 Objective\n\nUtilize **Local Measures of Spatial Autocorrelation (LMSA)** and **Emerging Hot Spot Analysis (EHSA):**\n\n-   To discover how bus mobility patterns differ across neighborhoods, providing deeper insights than global summary measures.\n-   To detect emerging patterns in urban mobility, helping planners anticipate commuting demands and design more responsive bus services and policies.\n\n# 3 Tasks\n\n## 3.1 Geospatial Data Science\n\n-   Derive an analytical hexagon data of 375m (this distance is the perpendicular distance between the centre of the hexagon and its edges) to represent the [traffic analysis zone (TAZ)](https://tmg.utoronto.ca/files/Reports/Traffic-Zone-Guidance_March-2021_Final.pdf).\n\n-   With reference to the time intervals provided in the table below, compute the passenger trips generated by origin at the hexagon level.\n\n    | Peak hour period       | Bus tap on time |\n    |------------------------|-----------------|\n    | Weekday morning peak   | 6am to 9am      |\n    | Weekday afternoon peak | 5pm to 8pm      |\n    | Weekend/holiday        | 11am to 8pm     |\n\n-   Display the geographical distribution of the passenger trips by using appropriate geovisualisation methods,\n\n-   Describe the spatial patterns revealed by the geovisualisation (not more than 200 words per visual).\n\n## 3.2 **LMSA Analysis**\n\n-   Compute LMSA statistic of the passengers trips generate by origin at hexagon level.\n-   Display the LMSA maps of the passengers trips generate by origin at hexagon level. The maps should only display the significant (i.e. p-value \\< 0.05)\n-   With reference to the analysis results, draw statistical conclusions (not more than 200 words per visual).\n\n## 3.3 **EHSA Analysis**\n\nWith reference to the passenger trips by origin at the hexagon level for the three time intervals given above:\n\n-   Perform Mann-Kendall Test by using the spatio-temporal local Gi\\* values,\n-   Prepared EHSA maps of the Gi\\* values of the passenger trips by origin at the hexagon level. The maps should only display the significant (i.e. p-value \\< 0.05).\n-   With reference to the EHSA maps and data visualisation prepared, describe the spatial patterns reveled. (not more than 250 words per cluster).\n\n# 4 The Data\n\nIn this exercise, 3 datasets will be used:\n\n-   **Aspatial: Passenger Volume by Origin Destination Bus Stops from LTA DataMall**\n\n    This dataset contains ridership information (datetime, total trips) showing the flow of passengers between bus stops across Singapore's public bus network.\n\n-   **Geospatial: Bus Stop Location from LTA DataMall**\n\n    This dataset provides the geographical coordinates and attributes of all bus stops in Singapore.\n\n-   **Geospatial: Master Plan 2019 Subzone Boundary (No Sea) from** **data.gov.sg**\n\n    This dataset contains polygon boundaries of Singapore's planning subzones as defined in the Urban Redevelopment Authority's (URA) Master Plan 2019.\n\n# 5 Download and Load the Packages\n\nWe first use p_load of pacman to download and load the revelent packages:\n\n| Library | Desc |\n|------------------------------------|------------------------------------|\n| [sf](https://r-spatial.github.io/sf/) | Handling geospatial data in R with support for simple features (points, lines, polygons) |\n| [tmap](https://r-tmap.github.io/tmap/) | Creating thematic maps and visualization for geospatial data |\n| [tidyverse](https://www.tidyverse.org) | A collection of packages for data manipulation and analysis, including readr (reading data), tidyr (tidying data), and dplyr (transforming data) |\n| [knitr](https://yihui.org/knitr/) | Generating elegant, flexible and fast dynamic reports that integrate code and output |\n| [sfdep](https://sfdep.josiahparry.com) | Creating spatial weights matrix objects from polygon contiguities for spatial dependence analysis |\n| [Kendall](https://cran.r-project.org/web/packages/Kendall/refman/Kendall.html#Kendall-package) | Computes the Kendall rank correlation and Mann-Kendall trend test |\n| [ggplot2](https://ggplot2.tidyverse.org) | Creating sophisticated data visualizations using the grammar of graphics approach |\n| [plotly](https://plotly.com/r/) | Building interactive web-based graphs and visualizations |\n| [patchwork](https://patchwork.data-imaginist.com) | Combining multiple ggplot2 plots into a single composition with flexible layout control |\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(sf, tmap, tidyverse, knitr,\n               sfdep, ggplot2, Kendall, plotly, patchwork,\n               ggridges)\n```\n:::\n\n\n\n# 6 Import & Prepare Data\n\n## 6.1 Import and Transform Geospatial Data\n\nWe first import **Master Plan 2019 Subzone Boundary** using `read_rds()` function, and then check its coordinate reference system (CRS) using `st_crs()`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz19 <- read_rds(\"data/rds/mpsz.rds\")\nst_crs(mpsz19)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\n\nThe result indicates that the MPSZ19 data is already in the SVY21 coordinate system (EPSG:3414), so no further adjustment is needed.\n\nNext, we import **Bus Stop Location Data** using `st_read()` of sf package and transform the EPSG from 9001 to 3414.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBusStop <- st_read(dsn = \"data/LTADataMall\", \n                 layer = \"BusStop\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `/Users/johsuan/johsuanh/ISSS626-GAA/Take-home/Take-home-Ex2/data/LTADataMall' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5172 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\nNext, we plot the bus stop locations using **tmap** before proceeding with further analysis:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz19)+\n  tm_polygons()+\ntm_shape(BusStop)+\n  tm_dots(size = 0.2)+\n  tm_layout(bg.color = \"#f6f6f6\",frame = FALSE)+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Bus Stop Locations\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n\nAs shown in the map, a few bus stops are located outside Singapore, likely near the Johor Bahru checkpoint in Malaysia. Since our analysis focuses on bus stops within Singapore, these bus stops will be removed from the study area.\n\nThe code below uses `st_join()` of **sf** package to clip the study area within SG:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBS_SG <- st_join(BusStop,mpsz19,\n                         join = st_within, left = FALSE)\n```\n:::\n\n\n\nLet's plot the map and check it again:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz19)+\n  tm_polygons()+\ntm_shape(BS_SG)+\n  tm_dots(size = 0.2)+\n  tm_layout(bg.color = \"#f6f6f6\",frame = FALSE)+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Bus Stop Locations in Singapore\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n\nNow, we can confirm the bus stops located outside of Singapore are all removed.\n\n## 6.2 Import and Prepare Aspatial Data\n\nThe code below use `read_csv` to import the lastest Aug 2025 bus trip data:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nodbus <- read_csv(\"data/LTADataMall/origin_destination_bus_202509.csv\")\n```\n:::\n\n\n\nWe first view the data and check its data structure:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(odbus))\n```\n\n::: {.cell-output-display}\n\n\n|YEAR_MONTH |DAY_TYPE | TIME_PER_HOUR|PT_TYPE |ORIGIN_PT_CODE |DESTINATION_PT_CODE | TOTAL_TRIPS|\n|:----------|:--------|-------------:|:-------|:--------------|:-------------------|-----------:|\n|2025-09    |WEEKDAY  |            13|BUS     |59259          |65439               |           2|\n|2025-09    |WEEKDAY  |            18|BUS     |71069          |58991               |           2|\n|2025-09    |WEEKDAY  |             6|BUS     |40441          |43429               |           1|\n|2025-09    |WEEKDAY  |            23|BUS     |17141          |20011               |           5|\n|2025-09    |WEEKDAY  |            17|BUS     |10018          |80009               |           1|\n|2025-09    |WEEKDAY  |            20|BUS     |16029          |15229               |           6|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(odbus)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nspc_tbl_ [5,707,191 × 7] (S3: spec_tbl_df/tbl_df/tbl/data.frame)\n $ YEAR_MONTH         : chr [1:5707191] \"2025-09\" \"2025-09\" \"2025-09\" \"2025-09\" ...\n $ DAY_TYPE           : chr [1:5707191] \"WEEKDAY\" \"WEEKDAY\" \"WEEKDAY\" \"WEEKDAY\" ...\n $ TIME_PER_HOUR      : num [1:5707191] 13 18 6 23 17 20 11 23 11 12 ...\n $ PT_TYPE            : chr [1:5707191] \"BUS\" \"BUS\" \"BUS\" \"BUS\" ...\n $ ORIGIN_PT_CODE     : chr [1:5707191] \"59259\" \"71069\" \"40441\" \"17141\" ...\n $ DESTINATION_PT_CODE: chr [1:5707191] \"65439\" \"58991\" \"43429\" \"20011\" ...\n $ TOTAL_TRIPS        : num [1:5707191] 2 2 1 5 1 6 3 2 19 1 ...\n - attr(*, \"spec\")=\n  .. cols(\n  ..   YEAR_MONTH = col_character(),\n  ..   DAY_TYPE = col_character(),\n  ..   TIME_PER_HOUR = col_double(),\n  ..   PT_TYPE = col_character(),\n  ..   ORIGIN_PT_CODE = col_character(),\n  ..   DESTINATION_PT_CODE = col_character(),\n  ..   TOTAL_TRIPS = col_double()\n  .. )\n - attr(*, \"problems\")=<externalptr> \n```\n\n\n:::\n:::\n\n\n\nAs shown in the summary above, this dataset contains 5,701,191 observations and 7 attributes. Although `ORIGIN_PT_CODE` and `DESTINATION_PT_CODE` are already in character format, we need to verify that **each** **bus stop code consists of five digits.**\n\n### 6.2.1 Aspatial Data Preperation\n\nWe first check if all bus stop codes are 5-digit using `nchar()` - number of char:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nall(nchar(odbus$ORIGIN_PT_CODE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n\n```{.r .cell-code}\nall(nchar(odbus$DESTINATION_PT_CODE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] TRUE\n```\n\n\n:::\n:::\n\n\n\nThe results indicate that all the numbers are 5 digits long, as they return the value “True”.\n\nThe code below renames the attributes for easier reference and combine data later and converts \"BUS_STOP_N\" into factor for further analysis:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips <- odbus %>%\n  select(-\"YEAR_MONTH\",-\"PT_TYPE\") %>%\n  rename(\"BUS_STOP_N\" = ORIGIN_PT_CODE) %>%\n  rename(\"Day_Type\" = DAY_TYPE) %>%\n  rename(\"Hour\" = TIME_PER_HOUR) %>%\n  rename(\"Trips\" = TOTAL_TRIPS)\n  #mutate(\"BUS_STOP_N\" = as.factor(\"BUS_STOP_N\"))\n\nkable(head(trips))\n```\n\n::: {.cell-output-display}\n\n\n|Day_Type | Hour|BUS_STOP_N |DESTINATION_PT_CODE | Trips|\n|:--------|----:|:----------|:-------------------|-----:|\n|WEEKDAY  |   13|59259      |65439               |     2|\n|WEEKDAY  |   18|71069      |58991               |     2|\n|WEEKDAY  |    6|40441      |43429               |     1|\n|WEEKDAY  |   23|17141      |20011               |     5|\n|WEEKDAY  |   17|10018      |80009               |     1|\n|WEEKDAY  |   20|16029      |15229               |     6|\n\n\n:::\n:::\n\n\n\nLastly, let's check the data summary\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(trips)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Day_Type              Hour        BUS_STOP_N        DESTINATION_PT_CODE\n Length:5707191     Min.   : 0.00   Length:5707191     Length:5707191     \n Class :character   1st Qu.:10.00   Class :character   Class :character   \n Mode  :character   Median :14.00   Mode  :character   Mode  :character   \n                    Mean   :14.03                                         \n                    3rd Qu.:18.00                                         \n                    Max.   :23.00                                         \n     Trips         \n Min.   :    1.00  \n 1st Qu.:    2.00  \n Median :    4.00  \n Mean   :   20.13  \n 3rd Qu.:   12.00  \n Max.   :34967.00  \n```\n\n\n:::\n:::\n\n\n\n# 7 EDA of Bus Routes data\n\n## 7.1 Trips Distribution\n\nLet's visualize the data to understand trips distribution through out Sep 2025:\n\n::: panel-tabset\n## Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist <- ggplot(trips, aes(x = Trips)) +\n  geom_histogram(bins = 30, fill = \"#93A4CC\", color = \"grey30\") +\n  labs(title = \"Histograms of Hour of Day and Trips\",\n       x = \"\", y = \"Frequency\") +\n  theme_minimal()+\n  theme(panel.background = element_rect(fill = \"#f6f6f6\"),\n        plot.background = element_rect(fill = \"#f6f6f6\",color = NA),\n        panel.grid = element_blank())\n\nbox <- ggplot(data=trips,aes(x=Trips))+\n  geom_boxplot(color=\"grey30\",fill=\"#93A4CC\")+\n  labs(\n       x = \"Trips\", y = \"\") +\n  theme_minimal()+\n  theme(panel.background = element_rect(fill = \"#f6f6f6\"),\n        plot.background = element_rect(fill = \"#f6f6f6\",color = NA),\n        panel.grid = element_blank())\n\nhist/box +\n  plot_annotation(theme = theme(\n    plot.background = element_rect(color= '#f6f6f6', linewidth = 0, fill =\"#f6f6f6\")))\n```\n:::\n\n\n:::\n\n::: callout-note\n## Observation\n\nThe distribution of trips is noticeably left-skewed, suggesting that certain bus routes experience a high concentration of activity during specific hours.\n:::\n\n## 7.2 Average Trips Distribution by Day of Hour and Day Type\n\nNext, let's check the distribution of trips by hour of day and day type. Before visualization, we need to summarize the average trips by Day_Type and hour first:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_summary <- trips %>%\n  group_by(Day_Type, Hour) %>%\n  summarise(avg_trips = mean(Trips, na.rm = TRUE),.groups = \"drop\")\n```\n:::\n\n\n\n::: panel-tabset\n## Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-16-1.png){width=1152}\n:::\n:::\n\n\n\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_summary$Day_Type <- factor(trips_summary$Day_Type, levels = c(\"WEEKENDS/HOLIDAY\",\"WEEKDAY\"))\n\nggplot(trips_summary, aes(x = Hour, y=Day_Type, fill = Day_Type, height = avg_trips, \n                          group = Day_Type)) +\n  geom_ridgeline(scale = 0.1, \n                 alpha = 0.7) +\n  scale_x_continuous(breaks = seq(0, 23, 1)) +\n  scale_fill_manual(values = c(\"#93A4CC\", \"#8EB859\"))+\n  labs(\n    title = \"Averafe Trips by Hour of Day and Day Type\",\n    x = \"Hour of Day\",\n    y = \"Frequency\"\n  ) +\n  geom_vline(xintercept = c(4, 7, 18), color = \"grey30\", \n             linetype = \"dashed\", linewidth = 0.6) +\n  theme_ridges()+\n  theme(\n    legend.position = \"none\",\n    plot.title = element_text(hjust = 0.5),\n    panel.background = element_rect(fill = \"#f6f6f6\"),\n    plot.background = element_rect(fill = \"#f6f6f6\", color = NA),\n    panel.grid = element_blank(),\n  )\n```\n:::\n\n\n:::\n\n::: callout-note\n## Observation\n\nOn weekdays, three distinct peak periods in bus usage are observed: 04:00 - 05:00 AM, 07:00–08:00 AM, and 18:00–19:00 PM. These peaks are likely driven by commuter traffic, particularly workers traveling to and from their workplaces. (The 4 AM peak is largely due to trips originating from JB into SG, for details, please refer to [8.5 Visualize Total Trips by Hexagon])\n\nDuring weekends and holidays, the distribution of trips is more flattened throughout the day, with a consistent average number of trips between 07:00 and 19:00.\n:::\n\n## 7.3 Number of Bus Stop by Subzone\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpsz19$n_bus_stop <-\n  lengths(st_intersects(mpsz19, BS_SG))\n```\n:::\n\n\n\n::: panel-tabset\n## Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz19)+\n  tm_polygons(fill = \"n_bus_stop\",\n              fill.scale = tm_scale_intervals(style = \"jenks\",\n                                              n=5))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Number of Bus Stops by Subzone\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n```\n:::\n\n\n:::\n\n::: callout-note\n## Observation\n\nAs shown on the map, Murai (87 bus stops), Tampines East (85), and Frankel (80) are the three subzones with the highest number of bus stops.\n:::\n\n## 7.4 Trips Volume by Subzone\n\nTo examine trip volumes by subzone, we first aggregate the number of trips by bus stop location and then perform a left join with the `mpsz19` sf data for plotting:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nBS_SG_joined <- BS_SG %>%\n   left_join(trips, by = \"BUS_STOP_N\")\n\nBS_SG_sz <- BS_SG_joined %>%\n  st_drop_geometry() %>%  # cos we need to combine data to mpsz\n  select(c(\"SUBZONE_C\",\"Trips\")) %>%\n  group_by(SUBZONE_C) %>%\n  summarise(total_trips = sum(Trips, na.rm = TRUE))\n\nmpsz19 <- mpsz19 %>% left_join(BS_SG_sz,by = \"SUBZONE_C\")\n```\n:::\n\n\n\n::: panel-tabset\n## Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::\n\n\n\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz19)+\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(style = \"jenks\",\n                                              n=5))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Trip Volume by Subzone\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n```\n:::\n\n\n:::\n\nLet's print the top 10 subzones with highest trip volume for reference:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTop_10_SZ <- mpsz19 %>%\n  arrange(desc(total_trips), desc(n_bus_stop)) %>%\n  slice(1:10)\n\nkable(Top_10_SZ)\n```\n\n::: {.cell-output-display}\n\n\n|REGION_N          |PLN_AREA_N  |SUBZONE_N                 |SUBZONE_C | n_bus_stop| total_trips|geometry                       |\n|:-----------------|:-----------|:-------------------------|:---------|----------:|-----------:|:------------------------------|\n|EAST REGION       |TAMPINES    |TAMPINES EAST             |TMSZ02    |         85|     3951285|MULTIPOLYGON (((42196.76 38... |\n|WEST REGION       |JURONG WEST |JURONG WEST CENTRAL       |JWSZ09    |         36|     2633606|MULTIPOLYGON (((13673.08 35... |\n|EAST REGION       |BEDOK       |BEDOK NORTH               |BDSZ04    |         56|     2558412|MULTIPOLYGON (((40284.24 35... |\n|NORTH REGION      |WOODLANDS   |WOODLANDS REGIONAL CENTRE |WDSZ01    |          9|     2082887|MULTIPOLYGON (((22734.02 46... |\n|NORTH REGION      |WOODLANDS   |NORTH COAST               |WDSZ09    |         18|     1730359|MULTIPOLYGON (((23491.93 49... |\n|CENTRAL REGION    |GEYLANG     |ALJUNIED                  |GLSZ04    |         45|     1641138|MULTIPOLYGON (((34449.13 33... |\n|EAST REGION       |TAMPINES    |TAMPINES WEST             |TMSZ03    |         55|     1531083|MULTIPOLYGON (((40632.19 35... |\n|NORTH-EAST REGION |SENGKANG    |SENGKANG TOWN CENTRE      |SESZ03    |         35|     1485037|MULTIPOLYGON (((35615.75 40... |\n|NORTH REGION      |WOODLANDS   |WOODLANDS EAST            |WDSZ03    |         51|     1415939|MULTIPOLYGON (((24786.75 46... |\n|NORTH-EAST REGION |SERANGOON   |SERANGOON CENTRAL         |SGSZ06    |         24|     1386907|MULTIPOLYGON (((32777.72 37... |\n\n\n:::\n:::\n\n\n\n::: callout-note\n## Observation\n\nTampines East appears on the list again, indicating that it has both a high number of bus stops and significant traffic volume. Observing the other subzones on the list, most contain major bus interchanges, suggesting that these areas serve as key transit hubs.\n:::\n\n# 8 Derive and Visualize Analytical Hexagons \n\nOne of the task is to derive an analytical hexagon data of 375m (this distance is the perpendicular distance between the centre of the hexagon and its edges) to represent the [traffic analysis zone (TAZ)](https://tmg.utoronto.ca/files/Reports/Traffic-Zone-Guidance_March-2021_Final.pdf).\n\nAccording to the documentation, the cell size of hexagonal cells refers to the distance between opposite edges. Therefore, the cell size in this case is 750 m.\n\nThe code below uses st_make_grid() to dervie the hexagon for TAZ:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon <- st_make_grid(mpsz19,\n                        cellsize = 750, \n                        what = \"polygon\",\n                        square = FALSE) %>% \n  st_sf()\n\nhexagon\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 3942 features and 0 fields\nGeometry type: POLYGON\nDimension:     XY\nBounding box:  xmin: 1917.538 ymin: 15315.71 xmax: 57042.54 ymax: 50606.24\nProjected CRS: SVY21 / Singapore TM\nFirst 10 features:\n                         geometry\n1  POLYGON ((2292.538 15965.23...\n2  POLYGON ((2292.538 17264.27...\n3  POLYGON ((2292.538 18563.3,...\n4  POLYGON ((2292.538 19862.34...\n5  POLYGON ((2292.538 21161.38...\n6  POLYGON ((2292.538 22460.42...\n7  POLYGON ((2292.538 23759.46...\n8  POLYGON ((2292.538 25058.49...\n9  POLYGON ((2292.538 26357.53...\n10 POLYGON ((2292.538 27656.57...\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(head(hexagon))\n```\n\n::: {.cell-output-display}\n\n\n|geometry                       |\n|:------------------------------|\n|POLYGON ((2292.538 15965.23... |\n|POLYGON ((2292.538 17264.27... |\n|POLYGON ((2292.538 18563.3,... |\n|POLYGON ((2292.538 19862.34... |\n|POLYGON ((2292.538 21161.38... |\n|POLYGON ((2292.538 22460.42... |\n\n\n:::\n:::\n\n\n\nNotice that the hexagon contains only one column with polygon geometry, lacking an unique ID. We need to map the hexagons with bus stops:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon$n_collisions <-\n  lengths(st_intersects(hexagon, BS_SG))\n\nkable(head(hexagon))\n```\n\n::: {.cell-output-display}\n\n\n|geometry                       | n_collisions|\n|:------------------------------|------------:|\n|POLYGON ((2292.538 15965.23... |            0|\n|POLYGON ((2292.538 17264.27... |            0|\n|POLYGON ((2292.538 18563.3,... |            0|\n|POLYGON ((2292.538 19862.34... |            0|\n|POLYGON ((2292.538 21161.38... |            0|\n|POLYGON ((2292.538 22460.42... |            0|\n\n\n:::\n:::\n\n\n\n## 8.1 Filter Hexagons for Study Area\n\nNext, we filter `n_collisions` greater than 0 for the study area:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon <- filter(hexagon,n_collisions>0)\ncount(hexagon)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSimple feature collection with 1 feature and 1 field\nGeometry type: MULTIPOLYGON\nDimension:     XY\nBounding box:  xmin: 3417.538 ymin: 26357.53 xmax: 48417.54 ymax: 50606.24\nProjected CRS: SVY21 / Singapore TM\n    n                       geometry\n1 834 MULTIPOLYGON (((4542.538 29...\n```\n\n\n:::\n:::\n\n\n\nThere are total 834 hexagon as our study area.\n\n## 8.2 Assign IDs to Each Hexagon\n\nWe need an unique identifier for each hexagon for reference. The code below defines and assigns new ID formatting in Hxxx for each hexagon:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhexagon <- hexagon %>%\n  select(,-n_collisions) # \"-\" means drop the n_collisions column\n\nhexagon$HEX_ID <- sprintf(\n  \"H%04d\", seq_len(nrow(hexagon))) %>%\n  as.factor()\n```\n:::\n\n\n\nNext, we plot our study area using tmap:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(mpsz19)+\n  tm_polygons()+\n  tm_shape(hexagon)+\n  tm_fill(col= \"black\",fill=\"#cc78aa\")+\n  tm_layout(bg.color = \"#f6f6f6\",frame = FALSE)+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Traffic Analysis Zone\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n\n## 8.3 Combine Hexagon ID with Trip Data\n\nWe first map Bus Stop code with Hexagon ID:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_hex <- st_intersection(\n  BS_SG, hexagon) %>%\n  st_drop_geometry() %>%\n  select(c(BUS_STOP_N, HEX_ID))%>%\n  distinct(BUS_STOP_N, .keep_all = TRUE)\n\n\nkable(head(bus_hex))\n```\n\n::: {.cell-output-display}\n\n\n|BUS_STOP_N |HEX_ID |\n|:----------|:------|\n|25059      |H0001  |\n|25751      |H0002  |\n|26379      |H0003  |\n|26299      |H0004  |\n|25761      |H0005  |\n|26399      |H0006  |\n\n\n:::\n:::\n\n\n\nNext, we use `inner_join()` to include the trips data within hexagon study areas:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips <- trips %>% \n  inner_join(bus_hex, by = \"BUS_STOP_N\")\n```\n:::\n\n\n\n## 8.4 Compute Total Trips by Peak Hour Period and Hexagon\n\nFollowing the task instructions, the `peak` variable was created using the `mutate()` and `case_when()` functions. However, based on the earlier EDA, where a peak was also observed between 4 AM and 5 AM, this time period has been included as part of the peak definition.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips <- trips %>%\n  mutate(\n    peak = case_when(\n      Day_Type == \"WEEKDAY\" & Hour >= 4 & Hour < 5  ~ \"Weekday 4 AM Peak\",\n      Day_Type == \"WEEKDAY\" & Hour >= 6 & Hour < 9  ~ \"Weekday AM Peak\",\n      Day_Type == \"WEEKDAY\" & Hour >= 17 & Hour < 20 ~ \"Weekday PM Peak\",\n      Day_Type == \"WEEKENDS/HOLIDAY\" & Hour >= 11 & Hour < 20 ~ \"Weekend/Holiday Peak\",\n      TRUE ~ \"Off Peak\"\n    )\n  )\n```\n:::\n\n\n\nNext, we sum up the total trips by HEX_ID and Peak hour period:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_summary_hex <- trips %>%\n  group_by(HEX_ID, peak) %>%\n  summarise(total_trips = sum(Trips, na.rm = TRUE), .groups = \"drop\") %>%  # drop grouping here\n  left_join(hexagon, by = \"HEX_ID\")%>%\n  st_sf()\n```\n:::\n\n\n\n## 8.5 Visualize Total Trips by Hexagon\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = trips_summary_hex) +\n  geom_histogram(aes(x = total_trips), bins = 30, fill = \"#93A4CC\", color = \"grey30\") +\n  labs(\n    title = \"Distribution of Total Trips by Hexagon\",\n    x = \"Total Trips\",\n    y = \"Count\"\n  ) +\n   theme_minimal()+\n  theme(panel.background = element_rect(fill = \"#f6f6f6\"),\n        plot.background = element_rect(fill = \"#f6f6f6\",color = NA),\n        panel.grid = element_blank())\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-35-1.png){width=672}\n:::\n:::\n\n\n\nSince the total trips during peak hours are still fairly left-skewed, we use \"jenks\" natural break method to highlight areas with disproportionately high values:\n\n::: panel-tabset\n## Plot\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Take-home_Ex02_files/figure-html/unnamed-chunk-36-1.png){width=1152}\n:::\n:::\n\n\n\n## Code\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nWD_4AM <- tm_shape(mpsz19)+\n  tm_polygons(fill_alpha = 0.5,lwd =0.5,col_alpha=0.5)+\ntm_shape(trips_summary_hex %>% filter (peak==\"Weekday 4 AM Peak\"))+\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(style = \"jenks\",\n                                              n=5))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Weekday AM Peak: 4-5\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n\nWK <- tm_shape(mpsz19)+\n  tm_polygons(fill_alpha = 0.5,lwd =0.5,col_alpha=0.5)+\ntm_shape(trips_summary_hex %>% filter (peak==\"Weekend/Holiday Peak\"))+\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(style = \"jenks\",\n                                              n=5))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Weekend/Holiday Peak: 11-20\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n\nWD_AM <- tm_shape(mpsz19)+\n  tm_polygons(fill_alpha = 0.5,lwd =0.5,col_alpha=0.5)+\ntm_shape(trips_summary_hex %>% filter (peak==\"Weekday AM Peak\"))+\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(style = \"jenks\",\n                                              n=5))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Weekday AM Peak: 6-9\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n\nWD_PM <- tm_shape(mpsz19)+\n  tm_polygons(fill_alpha = 0.5,lwd =0.5,col_alpha=0.5)+\ntm_shape(trips_summary_hex %>% filter (peak==\"Weekday PM Peak\"))+\n  tm_polygons(fill = \"total_trips\",\n              fill.scale = tm_scale_intervals(style = \"jenks\",\n                                              n=5))+\n  tm_layout(frame = FALSE,\n            bg.color = \"#f6f6f6\")+\n  tm_legend(frame = FALSE)+\n  tm_title(\"Weekday PM Peak: 17-20\",\n           position = tm_pos_out(\"center\", \"top\", \"center\"))\n\n\n\ntmap_arrange(WD_4AM,WD_AM, WD_PM,WK,ncol = 2,nrow=2)\n```\n:::\n\n\n:::\n\nNext, let's list out the top 5 Hexagon during each peak period:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrips_summary_hex <- st_join(trips_summary_hex,mpsz19,\n                         join = st_within, left = FALSE)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nkable(\n  trips_summary_hex %>%\n    filter(peak %in% c(\"Weekday AM Peak\", \"Weekday PM Peak\", \"Weekend/Holiday Peak\")) %>%\n    group_by(peak) %>%\n    slice_max(order_by = total_trips.x, n = 5, with_ties = FALSE) %>%\n    ungroup() %>%\n    select(HEX_ID, SUBZONE_N, peak, total_trips.x) %>%\n    arrange(peak, desc(total_trips.x))\n)\n```\n\n::: {.cell-output-display}\n\n\n|HEX_ID |SUBZONE_N           |peak                 | total_trips.x|geometry                       |\n|:------|:-------------------|:--------------------|-------------:|:------------------------------|\n|H0110  |JURONG WEST CENTRAL |Weekday AM Peak      |        327709|POLYGON ((13542.54 35450.8,... |\n|H0768  |TAMPINES EAST       |Weekday AM Peak      |        147727|POLYGON ((40542.54 36749.84... |\n|H0787  |TAMPINES EAST       |Weekday AM Peak      |        135690|POLYGON ((41667.54 37399.36... |\n|H0350  |WOODLANDS EAST      |Weekday AM Peak      |        101815|POLYGON ((24417.54 46492.62... |\n|H0400  |SEMBAWANG CENTRAL   |Weekday AM Peak      |         89974|POLYGON ((26292.54 47142.14... |\n|H0110  |JURONG WEST CENTRAL |Weekday PM Peak      |        421361|POLYGON ((13542.54 35450.8,... |\n|H0768  |TAMPINES EAST       |Weekday PM Peak      |        345191|POLYGON ((40542.54 36749.84... |\n|H0350  |WOODLANDS EAST      |Weekday PM Peak      |        122255|POLYGON ((24417.54 46492.62... |\n|H0787  |TAMPINES EAST       |Weekday PM Peak      |        115514|POLYGON ((41667.54 37399.36... |\n|H0400  |SEMBAWANG CENTRAL   |Weekday PM Peak      |        105086|POLYGON ((26292.54 47142.14... |\n|H0110  |JURONG WEST CENTRAL |Weekend/Holiday Peak |        249574|POLYGON ((13542.54 35450.8,... |\n|H0768  |TAMPINES EAST       |Weekend/Holiday Peak |        220168|POLYGON ((40542.54 36749.84... |\n|H0667  |GEYLANG EAST        |Weekend/Holiday Peak |         68603|POLYGON ((35292.54 32852.72... |\n|H0350  |WOODLANDS EAST      |Weekend/Holiday Peak |         67805|POLYGON ((24417.54 46492.62... |\n|H0400  |SEMBAWANG CENTRAL   |Weekend/Holiday Peak |         65968|POLYGON ((26292.54 47142.14... |\n\n\n:::\n:::\n\n\n\n::: callout-note\n## Observation\n\nAccording to [The Stait Time](https://www.straitstimes.com/singapore/singapores-cross-border-bus-services-to-start-leaving-jb-checkpoint-earlier-at-4-50am-on-weekdays), starting from Sep 15, the first buses of four Singapore-operated services departing from the Johor Bahru checkpoint to Woodlands on weekdays will begin operations earlier at 4:50 AM to help alleviate early morning traffic congestion at the Causeway.\n\nSince the plot above only includes bus trips originating from SG, it only partially reflects the early morning peak observed in the previous visualizations. Most buses operating around 4 AM originate from the JB checkpoint rather than from within Singapore.\n\nDuring both regular weekday and weekend peak hours, the busiest areas based on total trips are hexagons H0110, H0768, H0350, and H0400. These are located in the westernmost (Jurong West Central), easternmost (Tampines East), and northernmost regions (Sembawang Central and Woodlands East). Notably, H0667 (Geylang East) ranks as the third busiest area during weekend and holiday peak hours. In these areas, commuters are more likely to rely on buses due to limited or absent train service.\n:::\n\n# 9 LMSA Analysis - HCSA\n\nTo support the LMSA analysis, Hot Spot/Cold Spot analysis (HCSA) based on the Getis-Ord Gi\\* statistic will be performed.\n\n## 9.1 \n",
    "supporting": [
      "Take-home_Ex02_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}