---
title: "In-class Exercise 3b"
author: Huang Johsuan
date: "September 13, 2025"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

# 1 Import Libraries

```{r}
pacman::p_load(tidyverse,sf,tmap,httr,knitr)
```

# 2 Import Data

`map_dfr()` is used to import and append all the data in the same folder.

```{r}
#| eval: false
folder_path <- "data/ACRA"
file_list <- list.files(path = folder_path,
                        pattern = "^ACRA*.*\\.csv$",
                        full.names = TRUE)
acra <- file_list %>%
  map_dfr(read_csv)
```

## Export the file

```{r}
write_rds(acra_data,"data/rds/acra_data.rds")
```

```{r}
kable(head(acra_data,5))
```

```{r}
summary(acra_data)
```

# 2 Tyding ACRA Data

filter the industry - Restaurant:

```{r}
biz_5611 <- acra_data %>%
  select(1:24) %>%
  filter(primary_ssic_code == 56111) %>% # Restaurants
  rename(date = registration_incorporation_date) %>%
  mutate(date = as.Date(date),
         Year = year(date),
         Month_num = month(date,
                           label =TRUE,
                           abbr =TRUE)) %>%
  # make sure the post_code are 6 digits
  mutate(postal_code = str_pad(postal_code,
                               width =6,
                               side = "left",pad ="0"))  %>% 
  filter(Year == 2025)
```

# 3 Retrieve the Data

```{r}
postcodes <- unique(biz_5611$postal_code)

url <- "https://onemap.gov.sg/api/common/elastic/search"

found <- data.frame()
not_found <- data.frame(postcode =character())

for(pc in postcodes) {
  query <- list(
    searchVal = pc,
    returnGeom = "Y",
    getAddrDetails = "Y",
    pageNum ="1"
  )
  
  res <- GET(url, query=query)
  json <- content(res)
  
  if(json$found !=0) {
    df <- as.data.frame(json$results, stringFactors =FALSE)
    df$input_postcode <- pc
    found <- bind_rows(found,df)
  } else{
    not_found <- bind_rows(not_found, data.frame(postcode=pc))
  }
}
```

```{r}
biz_5611 <- biz_5611 %>%
  left_join(found,
            by = c('postal_code'='POSTAL'))


```

```{r}
biz_56111_sf <- st_as_sf(biz_5611,
                         coords = c("X","Y"),
                         crs=3414)
```
